// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/plugin/firewall.proto

package plugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FirewallRule represents a single firewall rule
type FirewallRule struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Direction: "inbound", "outbound", or "both"
	Direction string `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
	// Action: "allow", "deny", "drop", "reject"
	Action string `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	// Protocol: "tcp", "udp", "icmp", "any"
	Protocol string `protobuf:"bytes,6,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// Source criteria
	SourceIp   string `protobuf:"bytes,7,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`       // CIDR notation: "192.168.1.0/24" or "any"
	SourcePort string `protobuf:"bytes,8,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"` // Port or range: "80", "80-443", or "any"
	// Destination criteria
	DestIp   string `protobuf:"bytes,9,opt,name=dest_ip,json=destIp,proto3" json:"dest_ip,omitempty"`
	DestPort string `protobuf:"bytes,10,opt,name=dest_port,json=destPort,proto3" json:"dest_port,omitempty"`
	// Interface (optional)
	Interface string `protobuf:"bytes,11,opt,name=interface,proto3" json:"interface,omitempty"`
	// Priority/order (lower = higher priority)
	Priority int32 `protobuf:"varint,12,opt,name=priority,proto3" json:"priority,omitempty"`
	// Enabled state
	Enabled bool `protobuf:"varint,13,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Metadata
	CreatedAt     int64  `protobuf:"varint,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     int64  `protobuf:"varint,15,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`            // 0 = permanent
	Reason        string `protobuf:"bytes,16,opt,name=reason,proto3" json:"reason,omitempty"`                                    // Why this rule was created
	SourceService string `protobuf:"bytes,17,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"` // Which service created this rule
	// Statistics (read-only)
	HitCount      int64 `protobuf:"varint,18,opt,name=hit_count,json=hitCount,proto3" json:"hit_count,omitempty"`
	LastHitAt     int64 `protobuf:"varint,19,opt,name=last_hit_at,json=lastHitAt,proto3" json:"last_hit_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirewallRule) Reset() {
	*x = FirewallRule{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirewallRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirewallRule) ProtoMessage() {}

func (x *FirewallRule) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirewallRule.ProtoReflect.Descriptor instead.
func (*FirewallRule) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{0}
}

func (x *FirewallRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FirewallRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FirewallRule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FirewallRule) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *FirewallRule) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *FirewallRule) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *FirewallRule) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *FirewallRule) GetSourcePort() string {
	if x != nil {
		return x.SourcePort
	}
	return ""
}

func (x *FirewallRule) GetDestIp() string {
	if x != nil {
		return x.DestIp
	}
	return ""
}

func (x *FirewallRule) GetDestPort() string {
	if x != nil {
		return x.DestPort
	}
	return ""
}

func (x *FirewallRule) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *FirewallRule) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *FirewallRule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *FirewallRule) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *FirewallRule) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *FirewallRule) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *FirewallRule) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *FirewallRule) GetHitCount() int64 {
	if x != nil {
		return x.HitCount
	}
	return 0
}

func (x *FirewallRule) GetLastHitAt() int64 {
	if x != nil {
		return x.LastHitAt
	}
	return 0
}

// BlockedIP represents a blocked IP address
type BlockedIP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	SourceService string                 `protobuf:"bytes,3,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"` // e.g., "threat-intel", "conntrack", "manual"
	BlockedAt     int64                  `protobuf:"varint,4,opt,name=blocked_at,json=blockedAt,proto3" json:"blocked_at,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // 0 = permanent
	ThreatScore   int32                  `protobuf:"varint,6,opt,name=threat_score,json=threatScore,proto3" json:"threat_score,omitempty"`
	Categories    []string               `protobuf:"bytes,7,rep,name=categories,proto3" json:"categories,omitempty"` // e.g., "malware", "botnet", "scanner"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockedIP) Reset() {
	*x = BlockedIP{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockedIP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockedIP) ProtoMessage() {}

func (x *BlockedIP) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockedIP.ProtoReflect.Descriptor instead.
func (*BlockedIP) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{1}
}

func (x *BlockedIP) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *BlockedIP) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BlockedIP) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *BlockedIP) GetBlockedAt() int64 {
	if x != nil {
		return x.BlockedAt
	}
	return 0
}

func (x *BlockedIP) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *BlockedIP) GetThreatScore() int32 {
	if x != nil {
		return x.ThreatScore
	}
	return 0
}

func (x *BlockedIP) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

// FirewallStatus represents the current firewall state
type FirewallStatus struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Enabled             bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Backend             string                 `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"` // "iptables", "nftables", "pf", "windows-firewall"
	Version             string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"` // Backend version
	TotalRules          int32                  `protobuf:"varint,4,opt,name=total_rules,json=totalRules,proto3" json:"total_rules,omitempty"`
	ActiveRules         int32                  `protobuf:"varint,5,opt,name=active_rules,json=activeRules,proto3" json:"active_rules,omitempty"`
	BlockedIps          int32                  `protobuf:"varint,6,opt,name=blocked_ips,json=blockedIps,proto3" json:"blocked_ips,omitempty"`
	DefaultDenyInbound  bool                   `protobuf:"varint,7,opt,name=default_deny_inbound,json=defaultDenyInbound,proto3" json:"default_deny_inbound,omitempty"`
	DefaultDenyOutbound bool                   `protobuf:"varint,8,opt,name=default_deny_outbound,json=defaultDenyOutbound,proto3" json:"default_deny_outbound,omitempty"`
	LastUpdated         int64                  `protobuf:"varint,9,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	Capabilities        map[string]string      `protobuf:"bytes,10,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FirewallStatus) Reset() {
	*x = FirewallStatus{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirewallStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirewallStatus) ProtoMessage() {}

func (x *FirewallStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirewallStatus.ProtoReflect.Descriptor instead.
func (*FirewallStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{2}
}

func (x *FirewallStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *FirewallStatus) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *FirewallStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *FirewallStatus) GetTotalRules() int32 {
	if x != nil {
		return x.TotalRules
	}
	return 0
}

func (x *FirewallStatus) GetActiveRules() int32 {
	if x != nil {
		return x.ActiveRules
	}
	return 0
}

func (x *FirewallStatus) GetBlockedIps() int32 {
	if x != nil {
		return x.BlockedIps
	}
	return 0
}

func (x *FirewallStatus) GetDefaultDenyInbound() bool {
	if x != nil {
		return x.DefaultDenyInbound
	}
	return false
}

func (x *FirewallStatus) GetDefaultDenyOutbound() bool {
	if x != nil {
		return x.DefaultDenyOutbound
	}
	return false
}

func (x *FirewallStatus) GetLastUpdated() int64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

func (x *FirewallStatus) GetCapabilities() map[string]string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type FirewallEnableRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Enable              bool                   `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	DefaultDenyInbound  bool                   `protobuf:"varint,2,opt,name=default_deny_inbound,json=defaultDenyInbound,proto3" json:"default_deny_inbound,omitempty"`
	DefaultDenyOutbound bool                   `protobuf:"varint,3,opt,name=default_deny_outbound,json=defaultDenyOutbound,proto3" json:"default_deny_outbound,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FirewallEnableRequest) Reset() {
	*x = FirewallEnableRequest{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirewallEnableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirewallEnableRequest) ProtoMessage() {}

func (x *FirewallEnableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirewallEnableRequest.ProtoReflect.Descriptor instead.
func (*FirewallEnableRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{3}
}

func (x *FirewallEnableRequest) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *FirewallEnableRequest) GetDefaultDenyInbound() bool {
	if x != nil {
		return x.DefaultDenyInbound
	}
	return false
}

func (x *FirewallEnableRequest) GetDefaultDenyOutbound() bool {
	if x != nil {
		return x.DefaultDenyOutbound
	}
	return false
}

type FirewallEnableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Status        *FirewallStatus        `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirewallEnableResponse) Reset() {
	*x = FirewallEnableResponse{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirewallEnableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirewallEnableResponse) ProtoMessage() {}

func (x *FirewallEnableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirewallEnableResponse.ProtoReflect.Descriptor instead.
func (*FirewallEnableResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{4}
}

func (x *FirewallEnableResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FirewallEnableResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FirewallEnableResponse) GetStatus() *FirewallStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type FirewallStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirewallStatusRequest) Reset() {
	*x = FirewallStatusRequest{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirewallStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirewallStatusRequest) ProtoMessage() {}

func (x *FirewallStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirewallStatusRequest.ProtoReflect.Descriptor instead.
func (*FirewallStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{5}
}

type FirewallStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Status        *FirewallStatus        `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirewallStatusResponse) Reset() {
	*x = FirewallStatusResponse{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirewallStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirewallStatusResponse) ProtoMessage() {}

func (x *FirewallStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirewallStatusResponse.ProtoReflect.Descriptor instead.
func (*FirewallStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{6}
}

func (x *FirewallStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FirewallStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FirewallStatusResponse) GetStatus() *FirewallStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// Block/Unblock IP
type BlockIPRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ip              string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Reason          string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	SourceService   string                 `protobuf:"bytes,3,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"`
	DurationSeconds int64                  `protobuf:"varint,4,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"` // 0 = permanent
	ThreatScore     int32                  `protobuf:"varint,5,opt,name=threat_score,json=threatScore,proto3" json:"threat_score,omitempty"`
	Categories      []string               `protobuf:"bytes,6,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BlockIPRequest) Reset() {
	*x = BlockIPRequest{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockIPRequest) ProtoMessage() {}

func (x *BlockIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockIPRequest.ProtoReflect.Descriptor instead.
func (*BlockIPRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{7}
}

func (x *BlockIPRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *BlockIPRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BlockIPRequest) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *BlockIPRequest) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *BlockIPRequest) GetThreatScore() int32 {
	if x != nil {
		return x.ThreatScore
	}
	return 0
}

func (x *BlockIPRequest) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

type BlockIPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	BlockedIp     *BlockedIP             `protobuf:"bytes,3,opt,name=blocked_ip,json=blockedIp,proto3" json:"blocked_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockIPResponse) Reset() {
	*x = BlockIPResponse{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockIPResponse) ProtoMessage() {}

func (x *BlockIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockIPResponse.ProtoReflect.Descriptor instead.
func (*BlockIPResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{8}
}

func (x *BlockIPResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BlockIPResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *BlockIPResponse) GetBlockedIp() *BlockedIP {
	if x != nil {
		return x.BlockedIp
	}
	return nil
}

type UnblockIPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockIPRequest) Reset() {
	*x = UnblockIPRequest{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockIPRequest) ProtoMessage() {}

func (x *UnblockIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockIPRequest.ProtoReflect.Descriptor instead.
func (*UnblockIPRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{9}
}

func (x *UnblockIPRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type UnblockIPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockIPResponse) Reset() {
	*x = UnblockIPResponse{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockIPResponse) ProtoMessage() {}

func (x *UnblockIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockIPResponse.ProtoReflect.Descriptor instead.
func (*UnblockIPResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{10}
}

func (x *UnblockIPResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnblockIPResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListBlockedIPsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	SourceService string                 `protobuf:"bytes,3,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"` // Filter by source
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlockedIPsRequest) Reset() {
	*x = ListBlockedIPsRequest{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlockedIPsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlockedIPsRequest) ProtoMessage() {}

func (x *ListBlockedIPsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlockedIPsRequest.ProtoReflect.Descriptor instead.
func (*ListBlockedIPsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{11}
}

func (x *ListBlockedIPsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListBlockedIPsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListBlockedIPsRequest) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

type ListBlockedIPsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	BlockedIps    []*BlockedIP           `protobuf:"bytes,3,rep,name=blocked_ips,json=blockedIps,proto3" json:"blocked_ips,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlockedIPsResponse) Reset() {
	*x = ListBlockedIPsResponse{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlockedIPsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlockedIPsResponse) ProtoMessage() {}

func (x *ListBlockedIPsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlockedIPsResponse.ProtoReflect.Descriptor instead.
func (*ListBlockedIPsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{12}
}

func (x *ListBlockedIPsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListBlockedIPsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ListBlockedIPsResponse) GetBlockedIps() []*BlockedIP {
	if x != nil {
		return x.BlockedIps
	}
	return nil
}

func (x *ListBlockedIPsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type IsIPBlockedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsIPBlockedRequest) Reset() {
	*x = IsIPBlockedRequest{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsIPBlockedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsIPBlockedRequest) ProtoMessage() {}

func (x *IsIPBlockedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsIPBlockedRequest.ProtoReflect.Descriptor instead.
func (*IsIPBlockedRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{13}
}

func (x *IsIPBlockedRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type IsIPBlockedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Blocked       bool                   `protobuf:"varint,3,opt,name=blocked,proto3" json:"blocked,omitempty"`
	BlockedIp     *BlockedIP             `protobuf:"bytes,4,opt,name=blocked_ip,json=blockedIp,proto3" json:"blocked_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsIPBlockedResponse) Reset() {
	*x = IsIPBlockedResponse{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsIPBlockedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsIPBlockedResponse) ProtoMessage() {}

func (x *IsIPBlockedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsIPBlockedResponse.ProtoReflect.Descriptor instead.
func (*IsIPBlockedResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{14}
}

func (x *IsIPBlockedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IsIPBlockedResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *IsIPBlockedResponse) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

func (x *IsIPBlockedResponse) GetBlockedIp() *BlockedIP {
	if x != nil {
		return x.BlockedIp
	}
	return nil
}

// Rule Management
type AddRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *FirewallRule          `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRuleRequest) Reset() {
	*x = AddRuleRequest{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRuleRequest) ProtoMessage() {}

func (x *AddRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRuleRequest.ProtoReflect.Descriptor instead.
func (*AddRuleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{15}
}

func (x *AddRuleRequest) GetRule() *FirewallRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type AddRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Rule          *FirewallRule          `protobuf:"bytes,3,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRuleResponse) Reset() {
	*x = AddRuleResponse{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRuleResponse) ProtoMessage() {}

func (x *AddRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRuleResponse.ProtoReflect.Descriptor instead.
func (*AddRuleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{16}
}

func (x *AddRuleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddRuleResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AddRuleResponse) GetRule() *FirewallRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type RemoveRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRuleRequest) Reset() {
	*x = RemoveRuleRequest{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRuleRequest) ProtoMessage() {}

func (x *RemoveRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRuleRequest.ProtoReflect.Descriptor instead.
func (*RemoveRuleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{17}
}

func (x *RemoveRuleRequest) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

type RemoveRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRuleResponse) Reset() {
	*x = RemoveRuleResponse{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRuleResponse) ProtoMessage() {}

func (x *RemoveRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRuleResponse.ProtoReflect.Descriptor instead.
func (*RemoveRuleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{18}
}

func (x *RemoveRuleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveRuleResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *FirewallRule          `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRuleRequest) Reset() {
	*x = UpdateRuleRequest{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRuleRequest) ProtoMessage() {}

func (x *UpdateRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRuleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRuleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateRuleRequest) GetRule() *FirewallRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type UpdateRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Rule          *FirewallRule          `protobuf:"bytes,3,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRuleResponse) Reset() {
	*x = UpdateRuleResponse{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRuleResponse) ProtoMessage() {}

func (x *UpdateRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRuleResponse.ProtoReflect.Descriptor instead.
func (*UpdateRuleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateRuleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateRuleResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UpdateRuleResponse) GetRule() *FirewallRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type ListRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Direction     string                 `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"` // Filter by direction
	EnabledOnly   bool                   `protobuf:"varint,4,opt,name=enabled_only,json=enabledOnly,proto3" json:"enabled_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesRequest) Reset() {
	*x = ListRulesRequest{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesRequest) ProtoMessage() {}

func (x *ListRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesRequest.ProtoReflect.Descriptor instead.
func (*ListRulesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{21}
}

func (x *ListRulesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRulesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListRulesRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *ListRulesRequest) GetEnabledOnly() bool {
	if x != nil {
		return x.EnabledOnly
	}
	return false
}

type ListRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Rules         []*FirewallRule        `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesResponse) Reset() {
	*x = ListRulesResponse{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesResponse) ProtoMessage() {}

func (x *ListRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesResponse.ProtoReflect.Descriptor instead.
func (*ListRulesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{22}
}

func (x *ListRulesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListRulesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ListRulesResponse) GetRules() []*FirewallRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *ListRulesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuleRequest) Reset() {
	*x = GetRuleRequest{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleRequest) ProtoMessage() {}

func (x *GetRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleRequest.ProtoReflect.Descriptor instead.
func (*GetRuleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{23}
}

func (x *GetRuleRequest) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

type GetRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Rule          *FirewallRule          `protobuf:"bytes,3,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuleResponse) Reset() {
	*x = GetRuleResponse{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleResponse) ProtoMessage() {}

func (x *GetRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleResponse.ProtoReflect.Descriptor instead.
func (*GetRuleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{24}
}

func (x *GetRuleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetRuleResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetRuleResponse) GetRule() *FirewallRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

// Bulk Operations
type SyncBlocklistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockedIps    []*BlockedIP           `protobuf:"bytes,1,rep,name=blocked_ips,json=blockedIps,proto3" json:"blocked_ips,omitempty"`
	Replace       bool                   `protobuf:"varint,2,opt,name=replace,proto3" json:"replace,omitempty"` // true = replace all, false = merge
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncBlocklistRequest) Reset() {
	*x = SyncBlocklistRequest{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncBlocklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncBlocklistRequest) ProtoMessage() {}

func (x *SyncBlocklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncBlocklistRequest.ProtoReflect.Descriptor instead.
func (*SyncBlocklistRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{25}
}

func (x *SyncBlocklistRequest) GetBlockedIps() []*BlockedIP {
	if x != nil {
		return x.BlockedIps
	}
	return nil
}

func (x *SyncBlocklistRequest) GetReplace() bool {
	if x != nil {
		return x.Replace
	}
	return false
}

type SyncBlocklistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Added         int32                  `protobuf:"varint,3,opt,name=added,proto3" json:"added,omitempty"`
	Removed       int32                  `protobuf:"varint,4,opt,name=removed,proto3" json:"removed,omitempty"`
	Unchanged     int32                  `protobuf:"varint,5,opt,name=unchanged,proto3" json:"unchanged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncBlocklistResponse) Reset() {
	*x = SyncBlocklistResponse{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncBlocklistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncBlocklistResponse) ProtoMessage() {}

func (x *SyncBlocklistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncBlocklistResponse.ProtoReflect.Descriptor instead.
func (*SyncBlocklistResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{26}
}

func (x *SyncBlocklistResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncBlocklistResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SyncBlocklistResponse) GetAdded() int32 {
	if x != nil {
		return x.Added
	}
	return 0
}

func (x *SyncBlocklistResponse) GetRemoved() int32 {
	if x != nil {
		return x.Removed
	}
	return 0
}

func (x *SyncBlocklistResponse) GetUnchanged() int32 {
	if x != nil {
		return x.Unchanged
	}
	return 0
}

type FlushRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlushBlocks   bool                   `protobuf:"varint,1,opt,name=flush_blocks,json=flushBlocks,proto3" json:"flush_blocks,omitempty"`       // Flush IP blocks
	FlushRules    bool                   `protobuf:"varint,2,opt,name=flush_rules,json=flushRules,proto3" json:"flush_rules,omitempty"`          // Flush custom rules
	KeepEssential bool                   `protobuf:"varint,3,opt,name=keep_essential,json=keepEssential,proto3" json:"keep_essential,omitempty"` // Keep essential system rules
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushRulesRequest) Reset() {
	*x = FlushRulesRequest{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushRulesRequest) ProtoMessage() {}

func (x *FlushRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushRulesRequest.ProtoReflect.Descriptor instead.
func (*FlushRulesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{27}
}

func (x *FlushRulesRequest) GetFlushBlocks() bool {
	if x != nil {
		return x.FlushBlocks
	}
	return false
}

func (x *FlushRulesRequest) GetFlushRules() bool {
	if x != nil {
		return x.FlushRules
	}
	return false
}

func (x *FlushRulesRequest) GetKeepEssential() bool {
	if x != nil {
		return x.KeepEssential
	}
	return false
}

type FlushRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	RulesFlushed  int32                  `protobuf:"varint,3,opt,name=rules_flushed,json=rulesFlushed,proto3" json:"rules_flushed,omitempty"`
	BlocksFlushed int32                  `protobuf:"varint,4,opt,name=blocks_flushed,json=blocksFlushed,proto3" json:"blocks_flushed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushRulesResponse) Reset() {
	*x = FlushRulesResponse{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushRulesResponse) ProtoMessage() {}

func (x *FlushRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushRulesResponse.ProtoReflect.Descriptor instead.
func (*FlushRulesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{28}
}

func (x *FlushRulesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FlushRulesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FlushRulesResponse) GetRulesFlushed() int32 {
	if x != nil {
		return x.RulesFlushed
	}
	return 0
}

func (x *FlushRulesResponse) GetBlocksFlushed() int32 {
	if x != nil {
		return x.BlocksFlushed
	}
	return 0
}

// Port Management (convenience methods)
type OpenPortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`                 // "tcp", "udp", or "both"
	Direction     string                 `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"`               // "inbound", "outbound", or "both"
	SourceIp      string                 `protobuf:"bytes,4,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"` // Restrict to source (optional)
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenPortRequest) Reset() {
	*x = OpenPortRequest{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenPortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenPortRequest) ProtoMessage() {}

func (x *OpenPortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenPortRequest.ProtoReflect.Descriptor instead.
func (*OpenPortRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{29}
}

func (x *OpenPortRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *OpenPortRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *OpenPortRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *OpenPortRequest) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *OpenPortRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type OpenPortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Rule          *FirewallRule          `protobuf:"bytes,3,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenPortResponse) Reset() {
	*x = OpenPortResponse{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenPortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenPortResponse) ProtoMessage() {}

func (x *OpenPortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenPortResponse.ProtoReflect.Descriptor instead.
func (*OpenPortResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{30}
}

func (x *OpenPortResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OpenPortResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *OpenPortResponse) GetRule() *FirewallRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type ClosePortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Direction     string                 `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClosePortRequest) Reset() {
	*x = ClosePortRequest{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClosePortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClosePortRequest) ProtoMessage() {}

func (x *ClosePortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClosePortRequest.ProtoReflect.Descriptor instead.
func (*ClosePortRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{31}
}

func (x *ClosePortRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ClosePortRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ClosePortRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

type ClosePortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClosePortResponse) Reset() {
	*x = ClosePortResponse{}
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClosePortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClosePortResponse) ProtoMessage() {}

func (x *ClosePortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_firewall_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClosePortResponse.ProtoReflect.Descriptor instead.
func (*ClosePortResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_firewall_proto_rawDescGZIP(), []int{32}
}

func (x *ClosePortResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClosePortResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_proto_plugin_firewall_proto protoreflect.FileDescriptor

const file_api_proto_plugin_firewall_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/proto/plugin/firewall.proto\x12\fdarkd.plugin\x1a\x1dapi/proto/plugin/plugin.proto\"\xa8\x04\n" +
	"\fFirewallRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\tR\tdirection\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12\x1a\n" +
	"\bprotocol\x18\x06 \x01(\tR\bprotocol\x12\x1b\n" +
	"\tsource_ip\x18\a \x01(\tR\bsourceIp\x12\x1f\n" +
	"\vsource_port\x18\b \x01(\tR\n" +
	"sourcePort\x12\x17\n" +
	"\adest_ip\x18\t \x01(\tR\x06destIp\x12\x1b\n" +
	"\tdest_port\x18\n" +
	" \x01(\tR\bdestPort\x12\x1c\n" +
	"\tinterface\x18\v \x01(\tR\tinterface\x12\x1a\n" +
	"\bpriority\x18\f \x01(\x05R\bpriority\x12\x18\n" +
	"\aenabled\x18\r \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x0f \x01(\x03R\texpiresAt\x12\x16\n" +
	"\x06reason\x18\x10 \x01(\tR\x06reason\x12%\n" +
	"\x0esource_service\x18\x11 \x01(\tR\rsourceService\x12\x1b\n" +
	"\thit_count\x18\x12 \x01(\x03R\bhitCount\x12\x1e\n" +
	"\vlast_hit_at\x18\x13 \x01(\x03R\tlastHitAt\"\xdb\x01\n" +
	"\tBlockedIP\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12%\n" +
	"\x0esource_service\x18\x03 \x01(\tR\rsourceService\x12\x1d\n" +
	"\n" +
	"blocked_at\x18\x04 \x01(\x03R\tblockedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x03R\texpiresAt\x12!\n" +
	"\fthreat_score\x18\x06 \x01(\x05R\vthreatScore\x12\x1e\n" +
	"\n" +
	"categories\x18\a \x03(\tR\n" +
	"categories\"\xe1\x03\n" +
	"\x0eFirewallStatus\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x18\n" +
	"\abackend\x18\x02 \x01(\tR\abackend\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1f\n" +
	"\vtotal_rules\x18\x04 \x01(\x05R\n" +
	"totalRules\x12!\n" +
	"\factive_rules\x18\x05 \x01(\x05R\vactiveRules\x12\x1f\n" +
	"\vblocked_ips\x18\x06 \x01(\x05R\n" +
	"blockedIps\x120\n" +
	"\x14default_deny_inbound\x18\a \x01(\bR\x12defaultDenyInbound\x122\n" +
	"\x15default_deny_outbound\x18\b \x01(\bR\x13defaultDenyOutbound\x12!\n" +
	"\flast_updated\x18\t \x01(\x03R\vlastUpdated\x12R\n" +
	"\fcapabilities\x18\n" +
	" \x03(\v2..darkd.plugin.FirewallStatus.CapabilitiesEntryR\fcapabilities\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x95\x01\n" +
	"\x15FirewallEnableRequest\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\x120\n" +
	"\x14default_deny_inbound\x18\x02 \x01(\bR\x12defaultDenyInbound\x122\n" +
	"\x15default_deny_outbound\x18\x03 \x01(\bR\x13defaultDenyOutbound\"~\n" +
	"\x16FirewallEnableResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x124\n" +
	"\x06status\x18\x03 \x01(\v2\x1c.darkd.plugin.FirewallStatusR\x06status\"\x17\n" +
	"\x15FirewallStatusRequest\"~\n" +
	"\x16FirewallStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x124\n" +
	"\x06status\x18\x03 \x01(\v2\x1c.darkd.plugin.FirewallStatusR\x06status\"\xcd\x01\n" +
	"\x0eBlockIPRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12%\n" +
	"\x0esource_service\x18\x03 \x01(\tR\rsourceService\x12)\n" +
	"\x10duration_seconds\x18\x04 \x01(\x03R\x0fdurationSeconds\x12!\n" +
	"\fthreat_score\x18\x05 \x01(\x05R\vthreatScore\x12\x1e\n" +
	"\n" +
	"categories\x18\x06 \x03(\tR\n" +
	"categories\"y\n" +
	"\x0fBlockIPResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x126\n" +
	"\n" +
	"blocked_ip\x18\x03 \x01(\v2\x17.darkd.plugin.BlockedIPR\tblockedIp\"\"\n" +
	"\x10UnblockIPRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"C\n" +
	"\x11UnblockIPResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"l\n" +
	"\x15ListBlockedIPsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12%\n" +
	"\x0esource_service\x18\x03 \x01(\tR\rsourceService\"\xa3\x01\n" +
	"\x16ListBlockedIPsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x128\n" +
	"\vblocked_ips\x18\x03 \x03(\v2\x17.darkd.plugin.BlockedIPR\n" +
	"blockedIps\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\"$\n" +
	"\x12IsIPBlockedRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"\x97\x01\n" +
	"\x13IsIPBlockedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\ablocked\x18\x03 \x01(\bR\ablocked\x126\n" +
	"\n" +
	"blocked_ip\x18\x04 \x01(\v2\x17.darkd.plugin.BlockedIPR\tblockedIp\"@\n" +
	"\x0eAddRuleRequest\x12.\n" +
	"\x04rule\x18\x01 \x01(\v2\x1a.darkd.plugin.FirewallRuleR\x04rule\"q\n" +
	"\x0fAddRuleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12.\n" +
	"\x04rule\x18\x03 \x01(\v2\x1a.darkd.plugin.FirewallRuleR\x04rule\",\n" +
	"\x11RemoveRuleRequest\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\"D\n" +
	"\x12RemoveRuleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"C\n" +
	"\x11UpdateRuleRequest\x12.\n" +
	"\x04rule\x18\x01 \x01(\v2\x1a.darkd.plugin.FirewallRuleR\x04rule\"t\n" +
	"\x12UpdateRuleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12.\n" +
	"\x04rule\x18\x03 \x01(\v2\x1a.darkd.plugin.FirewallRuleR\x04rule\"\x81\x01\n" +
	"\x10ListRulesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\tR\tdirection\x12!\n" +
	"\fenabled_only\x18\x04 \x01(\bR\venabledOnly\"\x96\x01\n" +
	"\x11ListRulesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x120\n" +
	"\x05rules\x18\x03 \x03(\v2\x1a.darkd.plugin.FirewallRuleR\x05rules\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\")\n" +
	"\x0eGetRuleRequest\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\"q\n" +
	"\x0fGetRuleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12.\n" +
	"\x04rule\x18\x03 \x01(\v2\x1a.darkd.plugin.FirewallRuleR\x04rule\"j\n" +
	"\x14SyncBlocklistRequest\x128\n" +
	"\vblocked_ips\x18\x01 \x03(\v2\x17.darkd.plugin.BlockedIPR\n" +
	"blockedIps\x12\x18\n" +
	"\areplace\x18\x02 \x01(\bR\areplace\"\x95\x01\n" +
	"\x15SyncBlocklistResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x14\n" +
	"\x05added\x18\x03 \x01(\x05R\x05added\x12\x18\n" +
	"\aremoved\x18\x04 \x01(\x05R\aremoved\x12\x1c\n" +
	"\tunchanged\x18\x05 \x01(\x05R\tunchanged\"~\n" +
	"\x11FlushRulesRequest\x12!\n" +
	"\fflush_blocks\x18\x01 \x01(\bR\vflushBlocks\x12\x1f\n" +
	"\vflush_rules\x18\x02 \x01(\bR\n" +
	"flushRules\x12%\n" +
	"\x0ekeep_essential\x18\x03 \x01(\bR\rkeepEssential\"\x90\x01\n" +
	"\x12FlushRulesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12#\n" +
	"\rrules_flushed\x18\x03 \x01(\x05R\frulesFlushed\x12%\n" +
	"\x0eblocks_flushed\x18\x04 \x01(\x05R\rblocksFlushed\"\x9e\x01\n" +
	"\x0fOpenPortRequest\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\tR\tdirection\x12\x1b\n" +
	"\tsource_ip\x18\x04 \x01(\tR\bsourceIp\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"r\n" +
	"\x10OpenPortResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12.\n" +
	"\x04rule\x18\x03 \x01(\v2\x1a.darkd.plugin.FirewallRuleR\x04rule\"`\n" +
	"\x10ClosePortRequest\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\tR\tdirection\"C\n" +
	"\x11ClosePortResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\x8f\v\n" +
	"\x0eFirewallPlugin\x125\n" +
	"\x04Info\x12\x13.darkd.plugin.Empty\x1a\x18.darkd.plugin.PluginInfo\x12L\n" +
	"\tConfigure\x12\x1e.darkd.plugin.ConfigureRequest\x1a\x1f.darkd.plugin.ConfigureResponse\x12C\n" +
	"\x06Health\x12\x1b.darkd.plugin.HealthRequest\x1a\x1c.darkd.plugin.HealthResponse\x12S\n" +
	"\x06Enable\x12#.darkd.plugin.FirewallEnableRequest\x1a$.darkd.plugin.FirewallEnableResponse\x12S\n" +
	"\x06Status\x12#.darkd.plugin.FirewallStatusRequest\x1a$.darkd.plugin.FirewallStatusResponse\x12F\n" +
	"\aBlockIP\x12\x1c.darkd.plugin.BlockIPRequest\x1a\x1d.darkd.plugin.BlockIPResponse\x12L\n" +
	"\tUnblockIP\x12\x1e.darkd.plugin.UnblockIPRequest\x1a\x1f.darkd.plugin.UnblockIPResponse\x12[\n" +
	"\x0eListBlockedIPs\x12#.darkd.plugin.ListBlockedIPsRequest\x1a$.darkd.plugin.ListBlockedIPsResponse\x12R\n" +
	"\vIsIPBlocked\x12 .darkd.plugin.IsIPBlockedRequest\x1a!.darkd.plugin.IsIPBlockedResponse\x12F\n" +
	"\aAddRule\x12\x1c.darkd.plugin.AddRuleRequest\x1a\x1d.darkd.plugin.AddRuleResponse\x12O\n" +
	"\n" +
	"RemoveRule\x12\x1f.darkd.plugin.RemoveRuleRequest\x1a .darkd.plugin.RemoveRuleResponse\x12O\n" +
	"\n" +
	"UpdateRule\x12\x1f.darkd.plugin.UpdateRuleRequest\x1a .darkd.plugin.UpdateRuleResponse\x12L\n" +
	"\tListRules\x12\x1e.darkd.plugin.ListRulesRequest\x1a\x1f.darkd.plugin.ListRulesResponse\x12F\n" +
	"\aGetRule\x12\x1c.darkd.plugin.GetRuleRequest\x1a\x1d.darkd.plugin.GetRuleResponse\x12X\n" +
	"\rSyncBlocklist\x12\".darkd.plugin.SyncBlocklistRequest\x1a#.darkd.plugin.SyncBlocklistResponse\x12O\n" +
	"\n" +
	"FlushRules\x12\x1f.darkd.plugin.FlushRulesRequest\x1a .darkd.plugin.FlushRulesResponse\x12I\n" +
	"\bOpenPort\x12\x1d.darkd.plugin.OpenPortRequest\x1a\x1e.darkd.plugin.OpenPortResponse\x12L\n" +
	"\tClosePort\x12\x1e.darkd.plugin.ClosePortRequest\x1a\x1f.darkd.plugin.ClosePortResponseB:Z8github.com/afterdarksys/afterdark-darkd/api/proto/pluginb\x06proto3"

var (
	file_api_proto_plugin_firewall_proto_rawDescOnce sync.Once
	file_api_proto_plugin_firewall_proto_rawDescData []byte
)

func file_api_proto_plugin_firewall_proto_rawDescGZIP() []byte {
	file_api_proto_plugin_firewall_proto_rawDescOnce.Do(func() {
		file_api_proto_plugin_firewall_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_plugin_firewall_proto_rawDesc), len(file_api_proto_plugin_firewall_proto_rawDesc)))
	})
	return file_api_proto_plugin_firewall_proto_rawDescData
}

var file_api_proto_plugin_firewall_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_api_proto_plugin_firewall_proto_goTypes = []any{
	(*FirewallRule)(nil),           // 0: darkd.plugin.FirewallRule
	(*BlockedIP)(nil),              // 1: darkd.plugin.BlockedIP
	(*FirewallStatus)(nil),         // 2: darkd.plugin.FirewallStatus
	(*FirewallEnableRequest)(nil),  // 3: darkd.plugin.FirewallEnableRequest
	(*FirewallEnableResponse)(nil), // 4: darkd.plugin.FirewallEnableResponse
	(*FirewallStatusRequest)(nil),  // 5: darkd.plugin.FirewallStatusRequest
	(*FirewallStatusResponse)(nil), // 6: darkd.plugin.FirewallStatusResponse
	(*BlockIPRequest)(nil),         // 7: darkd.plugin.BlockIPRequest
	(*BlockIPResponse)(nil),        // 8: darkd.plugin.BlockIPResponse
	(*UnblockIPRequest)(nil),       // 9: darkd.plugin.UnblockIPRequest
	(*UnblockIPResponse)(nil),      // 10: darkd.plugin.UnblockIPResponse
	(*ListBlockedIPsRequest)(nil),  // 11: darkd.plugin.ListBlockedIPsRequest
	(*ListBlockedIPsResponse)(nil), // 12: darkd.plugin.ListBlockedIPsResponse
	(*IsIPBlockedRequest)(nil),     // 13: darkd.plugin.IsIPBlockedRequest
	(*IsIPBlockedResponse)(nil),    // 14: darkd.plugin.IsIPBlockedResponse
	(*AddRuleRequest)(nil),         // 15: darkd.plugin.AddRuleRequest
	(*AddRuleResponse)(nil),        // 16: darkd.plugin.AddRuleResponse
	(*RemoveRuleRequest)(nil),      // 17: darkd.plugin.RemoveRuleRequest
	(*RemoveRuleResponse)(nil),     // 18: darkd.plugin.RemoveRuleResponse
	(*UpdateRuleRequest)(nil),      // 19: darkd.plugin.UpdateRuleRequest
	(*UpdateRuleResponse)(nil),     // 20: darkd.plugin.UpdateRuleResponse
	(*ListRulesRequest)(nil),       // 21: darkd.plugin.ListRulesRequest
	(*ListRulesResponse)(nil),      // 22: darkd.plugin.ListRulesResponse
	(*GetRuleRequest)(nil),         // 23: darkd.plugin.GetRuleRequest
	(*GetRuleResponse)(nil),        // 24: darkd.plugin.GetRuleResponse
	(*SyncBlocklistRequest)(nil),   // 25: darkd.plugin.SyncBlocklistRequest
	(*SyncBlocklistResponse)(nil),  // 26: darkd.plugin.SyncBlocklistResponse
	(*FlushRulesRequest)(nil),      // 27: darkd.plugin.FlushRulesRequest
	(*FlushRulesResponse)(nil),     // 28: darkd.plugin.FlushRulesResponse
	(*OpenPortRequest)(nil),        // 29: darkd.plugin.OpenPortRequest
	(*OpenPortResponse)(nil),       // 30: darkd.plugin.OpenPortResponse
	(*ClosePortRequest)(nil),       // 31: darkd.plugin.ClosePortRequest
	(*ClosePortResponse)(nil),      // 32: darkd.plugin.ClosePortResponse
	nil,                            // 33: darkd.plugin.FirewallStatus.CapabilitiesEntry
	(*Empty)(nil),                  // 34: darkd.plugin.Empty
	(*ConfigureRequest)(nil),       // 35: darkd.plugin.ConfigureRequest
	(*HealthRequest)(nil),          // 36: darkd.plugin.HealthRequest
	(*PluginInfo)(nil),             // 37: darkd.plugin.PluginInfo
	(*ConfigureResponse)(nil),      // 38: darkd.plugin.ConfigureResponse
	(*HealthResponse)(nil),         // 39: darkd.plugin.HealthResponse
}
var file_api_proto_plugin_firewall_proto_depIdxs = []int32{
	33, // 0: darkd.plugin.FirewallStatus.capabilities:type_name -> darkd.plugin.FirewallStatus.CapabilitiesEntry
	2,  // 1: darkd.plugin.FirewallEnableResponse.status:type_name -> darkd.plugin.FirewallStatus
	2,  // 2: darkd.plugin.FirewallStatusResponse.status:type_name -> darkd.plugin.FirewallStatus
	1,  // 3: darkd.plugin.BlockIPResponse.blocked_ip:type_name -> darkd.plugin.BlockedIP
	1,  // 4: darkd.plugin.ListBlockedIPsResponse.blocked_ips:type_name -> darkd.plugin.BlockedIP
	1,  // 5: darkd.plugin.IsIPBlockedResponse.blocked_ip:type_name -> darkd.plugin.BlockedIP
	0,  // 6: darkd.plugin.AddRuleRequest.rule:type_name -> darkd.plugin.FirewallRule
	0,  // 7: darkd.plugin.AddRuleResponse.rule:type_name -> darkd.plugin.FirewallRule
	0,  // 8: darkd.plugin.UpdateRuleRequest.rule:type_name -> darkd.plugin.FirewallRule
	0,  // 9: darkd.plugin.UpdateRuleResponse.rule:type_name -> darkd.plugin.FirewallRule
	0,  // 10: darkd.plugin.ListRulesResponse.rules:type_name -> darkd.plugin.FirewallRule
	0,  // 11: darkd.plugin.GetRuleResponse.rule:type_name -> darkd.plugin.FirewallRule
	1,  // 12: darkd.plugin.SyncBlocklistRequest.blocked_ips:type_name -> darkd.plugin.BlockedIP
	0,  // 13: darkd.plugin.OpenPortResponse.rule:type_name -> darkd.plugin.FirewallRule
	34, // 14: darkd.plugin.FirewallPlugin.Info:input_type -> darkd.plugin.Empty
	35, // 15: darkd.plugin.FirewallPlugin.Configure:input_type -> darkd.plugin.ConfigureRequest
	36, // 16: darkd.plugin.FirewallPlugin.Health:input_type -> darkd.plugin.HealthRequest
	3,  // 17: darkd.plugin.FirewallPlugin.Enable:input_type -> darkd.plugin.FirewallEnableRequest
	5,  // 18: darkd.plugin.FirewallPlugin.Status:input_type -> darkd.plugin.FirewallStatusRequest
	7,  // 19: darkd.plugin.FirewallPlugin.BlockIP:input_type -> darkd.plugin.BlockIPRequest
	9,  // 20: darkd.plugin.FirewallPlugin.UnblockIP:input_type -> darkd.plugin.UnblockIPRequest
	11, // 21: darkd.plugin.FirewallPlugin.ListBlockedIPs:input_type -> darkd.plugin.ListBlockedIPsRequest
	13, // 22: darkd.plugin.FirewallPlugin.IsIPBlocked:input_type -> darkd.plugin.IsIPBlockedRequest
	15, // 23: darkd.plugin.FirewallPlugin.AddRule:input_type -> darkd.plugin.AddRuleRequest
	17, // 24: darkd.plugin.FirewallPlugin.RemoveRule:input_type -> darkd.plugin.RemoveRuleRequest
	19, // 25: darkd.plugin.FirewallPlugin.UpdateRule:input_type -> darkd.plugin.UpdateRuleRequest
	21, // 26: darkd.plugin.FirewallPlugin.ListRules:input_type -> darkd.plugin.ListRulesRequest
	23, // 27: darkd.plugin.FirewallPlugin.GetRule:input_type -> darkd.plugin.GetRuleRequest
	25, // 28: darkd.plugin.FirewallPlugin.SyncBlocklist:input_type -> darkd.plugin.SyncBlocklistRequest
	27, // 29: darkd.plugin.FirewallPlugin.FlushRules:input_type -> darkd.plugin.FlushRulesRequest
	29, // 30: darkd.plugin.FirewallPlugin.OpenPort:input_type -> darkd.plugin.OpenPortRequest
	31, // 31: darkd.plugin.FirewallPlugin.ClosePort:input_type -> darkd.plugin.ClosePortRequest
	37, // 32: darkd.plugin.FirewallPlugin.Info:output_type -> darkd.plugin.PluginInfo
	38, // 33: darkd.plugin.FirewallPlugin.Configure:output_type -> darkd.plugin.ConfigureResponse
	39, // 34: darkd.plugin.FirewallPlugin.Health:output_type -> darkd.plugin.HealthResponse
	4,  // 35: darkd.plugin.FirewallPlugin.Enable:output_type -> darkd.plugin.FirewallEnableResponse
	6,  // 36: darkd.plugin.FirewallPlugin.Status:output_type -> darkd.plugin.FirewallStatusResponse
	8,  // 37: darkd.plugin.FirewallPlugin.BlockIP:output_type -> darkd.plugin.BlockIPResponse
	10, // 38: darkd.plugin.FirewallPlugin.UnblockIP:output_type -> darkd.plugin.UnblockIPResponse
	12, // 39: darkd.plugin.FirewallPlugin.ListBlockedIPs:output_type -> darkd.plugin.ListBlockedIPsResponse
	14, // 40: darkd.plugin.FirewallPlugin.IsIPBlocked:output_type -> darkd.plugin.IsIPBlockedResponse
	16, // 41: darkd.plugin.FirewallPlugin.AddRule:output_type -> darkd.plugin.AddRuleResponse
	18, // 42: darkd.plugin.FirewallPlugin.RemoveRule:output_type -> darkd.plugin.RemoveRuleResponse
	20, // 43: darkd.plugin.FirewallPlugin.UpdateRule:output_type -> darkd.plugin.UpdateRuleResponse
	22, // 44: darkd.plugin.FirewallPlugin.ListRules:output_type -> darkd.plugin.ListRulesResponse
	24, // 45: darkd.plugin.FirewallPlugin.GetRule:output_type -> darkd.plugin.GetRuleResponse
	26, // 46: darkd.plugin.FirewallPlugin.SyncBlocklist:output_type -> darkd.plugin.SyncBlocklistResponse
	28, // 47: darkd.plugin.FirewallPlugin.FlushRules:output_type -> darkd.plugin.FlushRulesResponse
	30, // 48: darkd.plugin.FirewallPlugin.OpenPort:output_type -> darkd.plugin.OpenPortResponse
	32, // 49: darkd.plugin.FirewallPlugin.ClosePort:output_type -> darkd.plugin.ClosePortResponse
	32, // [32:50] is the sub-list for method output_type
	14, // [14:32] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_proto_plugin_firewall_proto_init() }
func file_api_proto_plugin_firewall_proto_init() {
	if File_api_proto_plugin_firewall_proto != nil {
		return
	}
	file_api_proto_plugin_plugin_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_plugin_firewall_proto_rawDesc), len(file_api_proto_plugin_firewall_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_plugin_firewall_proto_goTypes,
		DependencyIndexes: file_api_proto_plugin_firewall_proto_depIdxs,
		MessageInfos:      file_api_proto_plugin_firewall_proto_msgTypes,
	}.Build()
	File_api_proto_plugin_firewall_proto = out.File
	file_api_proto_plugin_firewall_proto_goTypes = nil
	file_api_proto_plugin_firewall_proto_depIdxs = nil
}
