// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: api/proto/plugin/firewall.proto

package plugin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FirewallPlugin_Info_FullMethodName           = "/darkd.plugin.FirewallPlugin/Info"
	FirewallPlugin_Configure_FullMethodName      = "/darkd.plugin.FirewallPlugin/Configure"
	FirewallPlugin_Health_FullMethodName         = "/darkd.plugin.FirewallPlugin/Health"
	FirewallPlugin_Enable_FullMethodName         = "/darkd.plugin.FirewallPlugin/Enable"
	FirewallPlugin_Status_FullMethodName         = "/darkd.plugin.FirewallPlugin/Status"
	FirewallPlugin_BlockIP_FullMethodName        = "/darkd.plugin.FirewallPlugin/BlockIP"
	FirewallPlugin_UnblockIP_FullMethodName      = "/darkd.plugin.FirewallPlugin/UnblockIP"
	FirewallPlugin_ListBlockedIPs_FullMethodName = "/darkd.plugin.FirewallPlugin/ListBlockedIPs"
	FirewallPlugin_IsIPBlocked_FullMethodName    = "/darkd.plugin.FirewallPlugin/IsIPBlocked"
	FirewallPlugin_AddRule_FullMethodName        = "/darkd.plugin.FirewallPlugin/AddRule"
	FirewallPlugin_RemoveRule_FullMethodName     = "/darkd.plugin.FirewallPlugin/RemoveRule"
	FirewallPlugin_UpdateRule_FullMethodName     = "/darkd.plugin.FirewallPlugin/UpdateRule"
	FirewallPlugin_ListRules_FullMethodName      = "/darkd.plugin.FirewallPlugin/ListRules"
	FirewallPlugin_GetRule_FullMethodName        = "/darkd.plugin.FirewallPlugin/GetRule"
	FirewallPlugin_SyncBlocklist_FullMethodName  = "/darkd.plugin.FirewallPlugin/SyncBlocklist"
	FirewallPlugin_FlushRules_FullMethodName     = "/darkd.plugin.FirewallPlugin/FlushRules"
	FirewallPlugin_OpenPort_FullMethodName       = "/darkd.plugin.FirewallPlugin/OpenPort"
	FirewallPlugin_ClosePort_FullMethodName      = "/darkd.plugin.FirewallPlugin/ClosePort"
)

// FirewallPluginClient is the client API for FirewallPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Firewall Plugin Service
type FirewallPluginClient interface {
	// Plugin lifecycle
	Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error)
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Firewall control
	Enable(ctx context.Context, in *FirewallEnableRequest, opts ...grpc.CallOption) (*FirewallEnableResponse, error)
	Status(ctx context.Context, in *FirewallStatusRequest, opts ...grpc.CallOption) (*FirewallStatusResponse, error)
	// IP blocking
	BlockIP(ctx context.Context, in *BlockIPRequest, opts ...grpc.CallOption) (*BlockIPResponse, error)
	UnblockIP(ctx context.Context, in *UnblockIPRequest, opts ...grpc.CallOption) (*UnblockIPResponse, error)
	ListBlockedIPs(ctx context.Context, in *ListBlockedIPsRequest, opts ...grpc.CallOption) (*ListBlockedIPsResponse, error)
	IsIPBlocked(ctx context.Context, in *IsIPBlockedRequest, opts ...grpc.CallOption) (*IsIPBlockedResponse, error)
	// Rule management
	AddRule(ctx context.Context, in *AddRuleRequest, opts ...grpc.CallOption) (*AddRuleResponse, error)
	RemoveRule(ctx context.Context, in *RemoveRuleRequest, opts ...grpc.CallOption) (*RemoveRuleResponse, error)
	UpdateRule(ctx context.Context, in *UpdateRuleRequest, opts ...grpc.CallOption) (*UpdateRuleResponse, error)
	ListRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error)
	GetRule(ctx context.Context, in *GetRuleRequest, opts ...grpc.CallOption) (*GetRuleResponse, error)
	// Bulk operations
	SyncBlocklist(ctx context.Context, in *SyncBlocklistRequest, opts ...grpc.CallOption) (*SyncBlocklistResponse, error)
	FlushRules(ctx context.Context, in *FlushRulesRequest, opts ...grpc.CallOption) (*FlushRulesResponse, error)
	// Port management
	OpenPort(ctx context.Context, in *OpenPortRequest, opts ...grpc.CallOption) (*OpenPortResponse, error)
	ClosePort(ctx context.Context, in *ClosePortRequest, opts ...grpc.CallOption) (*ClosePortResponse, error)
}

type firewallPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewFirewallPluginClient(cc grpc.ClientConnInterface) FirewallPluginClient {
	return &firewallPluginClient{cc}
}

func (c *firewallPluginClient) Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginInfo)
	err := c.cc.Invoke(ctx, FirewallPlugin_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewallPluginClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureResponse)
	err := c.cc.Invoke(ctx, FirewallPlugin_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewallPluginClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, FirewallPlugin_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewallPluginClient) Enable(ctx context.Context, in *FirewallEnableRequest, opts ...grpc.CallOption) (*FirewallEnableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FirewallEnableResponse)
	err := c.cc.Invoke(ctx, FirewallPlugin_Enable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewallPluginClient) Status(ctx context.Context, in *FirewallStatusRequest, opts ...grpc.CallOption) (*FirewallStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FirewallStatusResponse)
	err := c.cc.Invoke(ctx, FirewallPlugin_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewallPluginClient) BlockIP(ctx context.Context, in *BlockIPRequest, opts ...grpc.CallOption) (*BlockIPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlockIPResponse)
	err := c.cc.Invoke(ctx, FirewallPlugin_BlockIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewallPluginClient) UnblockIP(ctx context.Context, in *UnblockIPRequest, opts ...grpc.CallOption) (*UnblockIPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnblockIPResponse)
	err := c.cc.Invoke(ctx, FirewallPlugin_UnblockIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewallPluginClient) ListBlockedIPs(ctx context.Context, in *ListBlockedIPsRequest, opts ...grpc.CallOption) (*ListBlockedIPsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBlockedIPsResponse)
	err := c.cc.Invoke(ctx, FirewallPlugin_ListBlockedIPs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewallPluginClient) IsIPBlocked(ctx context.Context, in *IsIPBlockedRequest, opts ...grpc.CallOption) (*IsIPBlockedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsIPBlockedResponse)
	err := c.cc.Invoke(ctx, FirewallPlugin_IsIPBlocked_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewallPluginClient) AddRule(ctx context.Context, in *AddRuleRequest, opts ...grpc.CallOption) (*AddRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRuleResponse)
	err := c.cc.Invoke(ctx, FirewallPlugin_AddRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewallPluginClient) RemoveRule(ctx context.Context, in *RemoveRuleRequest, opts ...grpc.CallOption) (*RemoveRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveRuleResponse)
	err := c.cc.Invoke(ctx, FirewallPlugin_RemoveRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewallPluginClient) UpdateRule(ctx context.Context, in *UpdateRuleRequest, opts ...grpc.CallOption) (*UpdateRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRuleResponse)
	err := c.cc.Invoke(ctx, FirewallPlugin_UpdateRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewallPluginClient) ListRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRulesResponse)
	err := c.cc.Invoke(ctx, FirewallPlugin_ListRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewallPluginClient) GetRule(ctx context.Context, in *GetRuleRequest, opts ...grpc.CallOption) (*GetRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRuleResponse)
	err := c.cc.Invoke(ctx, FirewallPlugin_GetRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewallPluginClient) SyncBlocklist(ctx context.Context, in *SyncBlocklistRequest, opts ...grpc.CallOption) (*SyncBlocklistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncBlocklistResponse)
	err := c.cc.Invoke(ctx, FirewallPlugin_SyncBlocklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewallPluginClient) FlushRules(ctx context.Context, in *FlushRulesRequest, opts ...grpc.CallOption) (*FlushRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlushRulesResponse)
	err := c.cc.Invoke(ctx, FirewallPlugin_FlushRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewallPluginClient) OpenPort(ctx context.Context, in *OpenPortRequest, opts ...grpc.CallOption) (*OpenPortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenPortResponse)
	err := c.cc.Invoke(ctx, FirewallPlugin_OpenPort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewallPluginClient) ClosePort(ctx context.Context, in *ClosePortRequest, opts ...grpc.CallOption) (*ClosePortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClosePortResponse)
	err := c.cc.Invoke(ctx, FirewallPlugin_ClosePort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FirewallPluginServer is the server API for FirewallPlugin service.
// All implementations must embed UnimplementedFirewallPluginServer
// for forward compatibility.
//
// Firewall Plugin Service
type FirewallPluginServer interface {
	// Plugin lifecycle
	Info(context.Context, *Empty) (*PluginInfo, error)
	Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Firewall control
	Enable(context.Context, *FirewallEnableRequest) (*FirewallEnableResponse, error)
	Status(context.Context, *FirewallStatusRequest) (*FirewallStatusResponse, error)
	// IP blocking
	BlockIP(context.Context, *BlockIPRequest) (*BlockIPResponse, error)
	UnblockIP(context.Context, *UnblockIPRequest) (*UnblockIPResponse, error)
	ListBlockedIPs(context.Context, *ListBlockedIPsRequest) (*ListBlockedIPsResponse, error)
	IsIPBlocked(context.Context, *IsIPBlockedRequest) (*IsIPBlockedResponse, error)
	// Rule management
	AddRule(context.Context, *AddRuleRequest) (*AddRuleResponse, error)
	RemoveRule(context.Context, *RemoveRuleRequest) (*RemoveRuleResponse, error)
	UpdateRule(context.Context, *UpdateRuleRequest) (*UpdateRuleResponse, error)
	ListRules(context.Context, *ListRulesRequest) (*ListRulesResponse, error)
	GetRule(context.Context, *GetRuleRequest) (*GetRuleResponse, error)
	// Bulk operations
	SyncBlocklist(context.Context, *SyncBlocklistRequest) (*SyncBlocklistResponse, error)
	FlushRules(context.Context, *FlushRulesRequest) (*FlushRulesResponse, error)
	// Port management
	OpenPort(context.Context, *OpenPortRequest) (*OpenPortResponse, error)
	ClosePort(context.Context, *ClosePortRequest) (*ClosePortResponse, error)
	mustEmbedUnimplementedFirewallPluginServer()
}

// UnimplementedFirewallPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFirewallPluginServer struct{}

func (UnimplementedFirewallPluginServer) Info(context.Context, *Empty) (*PluginInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedFirewallPluginServer) Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedFirewallPluginServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedFirewallPluginServer) Enable(context.Context, *FirewallEnableRequest) (*FirewallEnableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enable not implemented")
}
func (UnimplementedFirewallPluginServer) Status(context.Context, *FirewallStatusRequest) (*FirewallStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedFirewallPluginServer) BlockIP(context.Context, *BlockIPRequest) (*BlockIPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BlockIP not implemented")
}
func (UnimplementedFirewallPluginServer) UnblockIP(context.Context, *UnblockIPRequest) (*UnblockIPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnblockIP not implemented")
}
func (UnimplementedFirewallPluginServer) ListBlockedIPs(context.Context, *ListBlockedIPsRequest) (*ListBlockedIPsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBlockedIPs not implemented")
}
func (UnimplementedFirewallPluginServer) IsIPBlocked(context.Context, *IsIPBlockedRequest) (*IsIPBlockedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsIPBlocked not implemented")
}
func (UnimplementedFirewallPluginServer) AddRule(context.Context, *AddRuleRequest) (*AddRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddRule not implemented")
}
func (UnimplementedFirewallPluginServer) RemoveRule(context.Context, *RemoveRuleRequest) (*RemoveRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveRule not implemented")
}
func (UnimplementedFirewallPluginServer) UpdateRule(context.Context, *UpdateRuleRequest) (*UpdateRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRule not implemented")
}
func (UnimplementedFirewallPluginServer) ListRules(context.Context, *ListRulesRequest) (*ListRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRules not implemented")
}
func (UnimplementedFirewallPluginServer) GetRule(context.Context, *GetRuleRequest) (*GetRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRule not implemented")
}
func (UnimplementedFirewallPluginServer) SyncBlocklist(context.Context, *SyncBlocklistRequest) (*SyncBlocklistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncBlocklist not implemented")
}
func (UnimplementedFirewallPluginServer) FlushRules(context.Context, *FlushRulesRequest) (*FlushRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FlushRules not implemented")
}
func (UnimplementedFirewallPluginServer) OpenPort(context.Context, *OpenPortRequest) (*OpenPortResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenPort not implemented")
}
func (UnimplementedFirewallPluginServer) ClosePort(context.Context, *ClosePortRequest) (*ClosePortResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClosePort not implemented")
}
func (UnimplementedFirewallPluginServer) mustEmbedUnimplementedFirewallPluginServer() {}
func (UnimplementedFirewallPluginServer) testEmbeddedByValue()                        {}

// UnsafeFirewallPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FirewallPluginServer will
// result in compilation errors.
type UnsafeFirewallPluginServer interface {
	mustEmbedUnimplementedFirewallPluginServer()
}

func RegisterFirewallPluginServer(s grpc.ServiceRegistrar, srv FirewallPluginServer) {
	// If the following call panics, it indicates UnimplementedFirewallPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FirewallPlugin_ServiceDesc, srv)
}

func _FirewallPlugin_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallPluginServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallPlugin_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallPluginServer).Info(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewallPlugin_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallPluginServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallPlugin_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallPluginServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewallPlugin_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallPluginServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallPlugin_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallPluginServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewallPlugin_Enable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FirewallEnableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallPluginServer).Enable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallPlugin_Enable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallPluginServer).Enable(ctx, req.(*FirewallEnableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewallPlugin_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FirewallStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallPluginServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallPlugin_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallPluginServer).Status(ctx, req.(*FirewallStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewallPlugin_BlockIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallPluginServer).BlockIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallPlugin_BlockIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallPluginServer).BlockIP(ctx, req.(*BlockIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewallPlugin_UnblockIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnblockIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallPluginServer).UnblockIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallPlugin_UnblockIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallPluginServer).UnblockIP(ctx, req.(*UnblockIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewallPlugin_ListBlockedIPs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBlockedIPsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallPluginServer).ListBlockedIPs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallPlugin_ListBlockedIPs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallPluginServer).ListBlockedIPs(ctx, req.(*ListBlockedIPsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewallPlugin_IsIPBlocked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsIPBlockedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallPluginServer).IsIPBlocked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallPlugin_IsIPBlocked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallPluginServer).IsIPBlocked(ctx, req.(*IsIPBlockedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewallPlugin_AddRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallPluginServer).AddRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallPlugin_AddRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallPluginServer).AddRule(ctx, req.(*AddRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewallPlugin_RemoveRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallPluginServer).RemoveRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallPlugin_RemoveRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallPluginServer).RemoveRule(ctx, req.(*RemoveRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewallPlugin_UpdateRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallPluginServer).UpdateRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallPlugin_UpdateRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallPluginServer).UpdateRule(ctx, req.(*UpdateRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewallPlugin_ListRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallPluginServer).ListRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallPlugin_ListRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallPluginServer).ListRules(ctx, req.(*ListRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewallPlugin_GetRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallPluginServer).GetRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallPlugin_GetRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallPluginServer).GetRule(ctx, req.(*GetRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewallPlugin_SyncBlocklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncBlocklistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallPluginServer).SyncBlocklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallPlugin_SyncBlocklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallPluginServer).SyncBlocklist(ctx, req.(*SyncBlocklistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewallPlugin_FlushRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallPluginServer).FlushRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallPlugin_FlushRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallPluginServer).FlushRules(ctx, req.(*FlushRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewallPlugin_OpenPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenPortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallPluginServer).OpenPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallPlugin_OpenPort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallPluginServer).OpenPort(ctx, req.(*OpenPortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewallPlugin_ClosePort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClosePortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewallPluginServer).ClosePort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewallPlugin_ClosePort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewallPluginServer).ClosePort(ctx, req.(*ClosePortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FirewallPlugin_ServiceDesc is the grpc.ServiceDesc for FirewallPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FirewallPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "darkd.plugin.FirewallPlugin",
	HandlerType: (*FirewallPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _FirewallPlugin_Info_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _FirewallPlugin_Configure_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _FirewallPlugin_Health_Handler,
		},
		{
			MethodName: "Enable",
			Handler:    _FirewallPlugin_Enable_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _FirewallPlugin_Status_Handler,
		},
		{
			MethodName: "BlockIP",
			Handler:    _FirewallPlugin_BlockIP_Handler,
		},
		{
			MethodName: "UnblockIP",
			Handler:    _FirewallPlugin_UnblockIP_Handler,
		},
		{
			MethodName: "ListBlockedIPs",
			Handler:    _FirewallPlugin_ListBlockedIPs_Handler,
		},
		{
			MethodName: "IsIPBlocked",
			Handler:    _FirewallPlugin_IsIPBlocked_Handler,
		},
		{
			MethodName: "AddRule",
			Handler:    _FirewallPlugin_AddRule_Handler,
		},
		{
			MethodName: "RemoveRule",
			Handler:    _FirewallPlugin_RemoveRule_Handler,
		},
		{
			MethodName: "UpdateRule",
			Handler:    _FirewallPlugin_UpdateRule_Handler,
		},
		{
			MethodName: "ListRules",
			Handler:    _FirewallPlugin_ListRules_Handler,
		},
		{
			MethodName: "GetRule",
			Handler:    _FirewallPlugin_GetRule_Handler,
		},
		{
			MethodName: "SyncBlocklist",
			Handler:    _FirewallPlugin_SyncBlocklist_Handler,
		},
		{
			MethodName: "FlushRules",
			Handler:    _FirewallPlugin_FlushRules_Handler,
		},
		{
			MethodName: "OpenPort",
			Handler:    _FirewallPlugin_OpenPort_Handler,
		},
		{
			MethodName: "ClosePort",
			Handler:    _FirewallPlugin_ClosePort_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/plugin/firewall.proto",
}
