// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: api/proto/plugin/plugin.proto

package plugin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServicePlugin_Info_FullMethodName      = "/darkd.plugin.ServicePlugin/Info"
	ServicePlugin_Configure_FullMethodName = "/darkd.plugin.ServicePlugin/Configure"
	ServicePlugin_Start_FullMethodName     = "/darkd.plugin.ServicePlugin/Start"
	ServicePlugin_Stop_FullMethodName      = "/darkd.plugin.ServicePlugin/Stop"
	ServicePlugin_Health_FullMethodName    = "/darkd.plugin.ServicePlugin/Health"
	ServicePlugin_Execute_FullMethodName   = "/darkd.plugin.ServicePlugin/Execute"
)

// ServicePluginClient is the client API for ServicePlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServicePluginClient interface {
	Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error)
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
	Start(ctx context.Context, in *ServiceStartRequest, opts ...grpc.CallOption) (*ServiceStartResponse, error)
	Stop(ctx context.Context, in *ServiceStopRequest, opts ...grpc.CallOption) (*ServiceStopResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Execute(ctx context.Context, in *ServiceExecuteRequest, opts ...grpc.CallOption) (*ServiceExecuteResponse, error)
}

type servicePluginClient struct {
	cc grpc.ClientConnInterface
}

func NewServicePluginClient(cc grpc.ClientConnInterface) ServicePluginClient {
	return &servicePluginClient{cc}
}

func (c *servicePluginClient) Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginInfo)
	err := c.cc.Invoke(ctx, ServicePlugin_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicePluginClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureResponse)
	err := c.cc.Invoke(ctx, ServicePlugin_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicePluginClient) Start(ctx context.Context, in *ServiceStartRequest, opts ...grpc.CallOption) (*ServiceStartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceStartResponse)
	err := c.cc.Invoke(ctx, ServicePlugin_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicePluginClient) Stop(ctx context.Context, in *ServiceStopRequest, opts ...grpc.CallOption) (*ServiceStopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceStopResponse)
	err := c.cc.Invoke(ctx, ServicePlugin_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicePluginClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ServicePlugin_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicePluginClient) Execute(ctx context.Context, in *ServiceExecuteRequest, opts ...grpc.CallOption) (*ServiceExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceExecuteResponse)
	err := c.cc.Invoke(ctx, ServicePlugin_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServicePluginServer is the server API for ServicePlugin service.
// All implementations must embed UnimplementedServicePluginServer
// for forward compatibility.
type ServicePluginServer interface {
	Info(context.Context, *Empty) (*PluginInfo, error)
	Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	Start(context.Context, *ServiceStartRequest) (*ServiceStartResponse, error)
	Stop(context.Context, *ServiceStopRequest) (*ServiceStopResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Execute(context.Context, *ServiceExecuteRequest) (*ServiceExecuteResponse, error)
	mustEmbedUnimplementedServicePluginServer()
}

// UnimplementedServicePluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServicePluginServer struct{}

func (UnimplementedServicePluginServer) Info(context.Context, *Empty) (*PluginInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedServicePluginServer) Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedServicePluginServer) Start(context.Context, *ServiceStartRequest) (*ServiceStartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedServicePluginServer) Stop(context.Context, *ServiceStopRequest) (*ServiceStopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedServicePluginServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedServicePluginServer) Execute(context.Context, *ServiceExecuteRequest) (*ServiceExecuteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedServicePluginServer) mustEmbedUnimplementedServicePluginServer() {}
func (UnimplementedServicePluginServer) testEmbeddedByValue()                       {}

// UnsafeServicePluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServicePluginServer will
// result in compilation errors.
type UnsafeServicePluginServer interface {
	mustEmbedUnimplementedServicePluginServer()
}

func RegisterServicePluginServer(s grpc.ServiceRegistrar, srv ServicePluginServer) {
	// If the following call panics, it indicates UnimplementedServicePluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServicePlugin_ServiceDesc, srv)
}

func _ServicePlugin_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicePluginServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicePlugin_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicePluginServer).Info(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicePlugin_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicePluginServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicePlugin_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicePluginServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicePlugin_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicePluginServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicePlugin_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicePluginServer).Start(ctx, req.(*ServiceStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicePlugin_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceStopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicePluginServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicePlugin_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicePluginServer).Stop(ctx, req.(*ServiceStopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicePlugin_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicePluginServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicePlugin_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicePluginServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicePlugin_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicePluginServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicePlugin_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicePluginServer).Execute(ctx, req.(*ServiceExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServicePlugin_ServiceDesc is the grpc.ServiceDesc for ServicePlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServicePlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "darkd.plugin.ServicePlugin",
	HandlerType: (*ServicePluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _ServicePlugin_Info_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _ServicePlugin_Configure_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _ServicePlugin_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _ServicePlugin_Stop_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _ServicePlugin_Health_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _ServicePlugin_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/plugin/plugin.proto",
}

const (
	DataSourcePlugin_Info_FullMethodName       = "/darkd.plugin.DataSourcePlugin/Info"
	DataSourcePlugin_Configure_FullMethodName  = "/darkd.plugin.DataSourcePlugin/Configure"
	DataSourcePlugin_Connect_FullMethodName    = "/darkd.plugin.DataSourcePlugin/Connect"
	DataSourcePlugin_Disconnect_FullMethodName = "/darkd.plugin.DataSourcePlugin/Disconnect"
	DataSourcePlugin_Query_FullMethodName      = "/darkd.plugin.DataSourcePlugin/Query"
	DataSourcePlugin_Subscribe_FullMethodName  = "/darkd.plugin.DataSourcePlugin/Subscribe"
	DataSourcePlugin_Health_FullMethodName     = "/darkd.plugin.DataSourcePlugin/Health"
)

// DataSourcePluginClient is the client API for DataSourcePlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataSourcePluginClient interface {
	Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error)
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
	Connect(ctx context.Context, in *DataSourceConnectRequest, opts ...grpc.CallOption) (*DataSourceConnectResponse, error)
	Disconnect(ctx context.Context, in *DataSourceDisconnectRequest, opts ...grpc.CallOption) (*DataSourceDisconnectResponse, error)
	Query(ctx context.Context, in *DataSourceQueryRequest, opts ...grpc.CallOption) (*DataSourceQueryResponse, error)
	Subscribe(ctx context.Context, in *DataSourceSubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataSourceSubscribeResponse], error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type dataSourcePluginClient struct {
	cc grpc.ClientConnInterface
}

func NewDataSourcePluginClient(cc grpc.ClientConnInterface) DataSourcePluginClient {
	return &dataSourcePluginClient{cc}
}

func (c *dataSourcePluginClient) Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginInfo)
	err := c.cc.Invoke(ctx, DataSourcePlugin_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourcePluginClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureResponse)
	err := c.cc.Invoke(ctx, DataSourcePlugin_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourcePluginClient) Connect(ctx context.Context, in *DataSourceConnectRequest, opts ...grpc.CallOption) (*DataSourceConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataSourceConnectResponse)
	err := c.cc.Invoke(ctx, DataSourcePlugin_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourcePluginClient) Disconnect(ctx context.Context, in *DataSourceDisconnectRequest, opts ...grpc.CallOption) (*DataSourceDisconnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataSourceDisconnectResponse)
	err := c.cc.Invoke(ctx, DataSourcePlugin_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourcePluginClient) Query(ctx context.Context, in *DataSourceQueryRequest, opts ...grpc.CallOption) (*DataSourceQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataSourceQueryResponse)
	err := c.cc.Invoke(ctx, DataSourcePlugin_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourcePluginClient) Subscribe(ctx context.Context, in *DataSourceSubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataSourceSubscribeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataSourcePlugin_ServiceDesc.Streams[0], DataSourcePlugin_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DataSourceSubscribeRequest, DataSourceSubscribeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataSourcePlugin_SubscribeClient = grpc.ServerStreamingClient[DataSourceSubscribeResponse]

func (c *dataSourcePluginClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, DataSourcePlugin_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataSourcePluginServer is the server API for DataSourcePlugin service.
// All implementations must embed UnimplementedDataSourcePluginServer
// for forward compatibility.
type DataSourcePluginServer interface {
	Info(context.Context, *Empty) (*PluginInfo, error)
	Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	Connect(context.Context, *DataSourceConnectRequest) (*DataSourceConnectResponse, error)
	Disconnect(context.Context, *DataSourceDisconnectRequest) (*DataSourceDisconnectResponse, error)
	Query(context.Context, *DataSourceQueryRequest) (*DataSourceQueryResponse, error)
	Subscribe(*DataSourceSubscribeRequest, grpc.ServerStreamingServer[DataSourceSubscribeResponse]) error
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedDataSourcePluginServer()
}

// UnimplementedDataSourcePluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataSourcePluginServer struct{}

func (UnimplementedDataSourcePluginServer) Info(context.Context, *Empty) (*PluginInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedDataSourcePluginServer) Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedDataSourcePluginServer) Connect(context.Context, *DataSourceConnectRequest) (*DataSourceConnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedDataSourcePluginServer) Disconnect(context.Context, *DataSourceDisconnectRequest) (*DataSourceDisconnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedDataSourcePluginServer) Query(context.Context, *DataSourceQueryRequest) (*DataSourceQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedDataSourcePluginServer) Subscribe(*DataSourceSubscribeRequest, grpc.ServerStreamingServer[DataSourceSubscribeResponse]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedDataSourcePluginServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedDataSourcePluginServer) mustEmbedUnimplementedDataSourcePluginServer() {}
func (UnimplementedDataSourcePluginServer) testEmbeddedByValue()                          {}

// UnsafeDataSourcePluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataSourcePluginServer will
// result in compilation errors.
type UnsafeDataSourcePluginServer interface {
	mustEmbedUnimplementedDataSourcePluginServer()
}

func RegisterDataSourcePluginServer(s grpc.ServiceRegistrar, srv DataSourcePluginServer) {
	// If the following call panics, it indicates UnimplementedDataSourcePluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataSourcePlugin_ServiceDesc, srv)
}

func _DataSourcePlugin_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourcePluginServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourcePlugin_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourcePluginServer).Info(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourcePlugin_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourcePluginServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourcePlugin_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourcePluginServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourcePlugin_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataSourceConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourcePluginServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourcePlugin_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourcePluginServer).Connect(ctx, req.(*DataSourceConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourcePlugin_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataSourceDisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourcePluginServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourcePlugin_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourcePluginServer).Disconnect(ctx, req.(*DataSourceDisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourcePlugin_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataSourceQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourcePluginServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourcePlugin_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourcePluginServer).Query(ctx, req.(*DataSourceQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourcePlugin_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DataSourceSubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataSourcePluginServer).Subscribe(m, &grpc.GenericServerStream[DataSourceSubscribeRequest, DataSourceSubscribeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataSourcePlugin_SubscribeServer = grpc.ServerStreamingServer[DataSourceSubscribeResponse]

func _DataSourcePlugin_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourcePluginServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourcePlugin_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourcePluginServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataSourcePlugin_ServiceDesc is the grpc.ServiceDesc for DataSourcePlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataSourcePlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "darkd.plugin.DataSourcePlugin",
	HandlerType: (*DataSourcePluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _DataSourcePlugin_Info_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _DataSourcePlugin_Configure_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _DataSourcePlugin_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _DataSourcePlugin_Disconnect_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _DataSourcePlugin_Query_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _DataSourcePlugin_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _DataSourcePlugin_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/plugin/plugin.proto",
}

const (
	StoragePlugin_Info_FullMethodName       = "/darkd.plugin.StoragePlugin/Info"
	StoragePlugin_Configure_FullMethodName  = "/darkd.plugin.StoragePlugin/Configure"
	StoragePlugin_Connect_FullMethodName    = "/darkd.plugin.StoragePlugin/Connect"
	StoragePlugin_Disconnect_FullMethodName = "/darkd.plugin.StoragePlugin/Disconnect"
	StoragePlugin_Get_FullMethodName        = "/darkd.plugin.StoragePlugin/Get"
	StoragePlugin_Set_FullMethodName        = "/darkd.plugin.StoragePlugin/Set"
	StoragePlugin_Delete_FullMethodName     = "/darkd.plugin.StoragePlugin/Delete"
	StoragePlugin_List_FullMethodName       = "/darkd.plugin.StoragePlugin/List"
	StoragePlugin_Query_FullMethodName      = "/darkd.plugin.StoragePlugin/Query"
	StoragePlugin_Health_FullMethodName     = "/darkd.plugin.StoragePlugin/Health"
)

// StoragePluginClient is the client API for StoragePlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StoragePluginClient interface {
	Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error)
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
	Connect(ctx context.Context, in *StorageConnectRequest, opts ...grpc.CallOption) (*StorageConnectResponse, error)
	Disconnect(ctx context.Context, in *StorageDisconnectRequest, opts ...grpc.CallOption) (*StorageDisconnectResponse, error)
	Get(ctx context.Context, in *StorageGetRequest, opts ...grpc.CallOption) (*StorageGetResponse, error)
	Set(ctx context.Context, in *StorageSetRequest, opts ...grpc.CallOption) (*StorageSetResponse, error)
	Delete(ctx context.Context, in *StorageDeleteRequest, opts ...grpc.CallOption) (*StorageDeleteResponse, error)
	List(ctx context.Context, in *StorageListRequest, opts ...grpc.CallOption) (*StorageListResponse, error)
	Query(ctx context.Context, in *StorageQueryRequest, opts ...grpc.CallOption) (*StorageQueryResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type storagePluginClient struct {
	cc grpc.ClientConnInterface
}

func NewStoragePluginClient(cc grpc.ClientConnInterface) StoragePluginClient {
	return &storagePluginClient{cc}
}

func (c *storagePluginClient) Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginInfo)
	err := c.cc.Invoke(ctx, StoragePlugin_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storagePluginClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureResponse)
	err := c.cc.Invoke(ctx, StoragePlugin_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storagePluginClient) Connect(ctx context.Context, in *StorageConnectRequest, opts ...grpc.CallOption) (*StorageConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageConnectResponse)
	err := c.cc.Invoke(ctx, StoragePlugin_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storagePluginClient) Disconnect(ctx context.Context, in *StorageDisconnectRequest, opts ...grpc.CallOption) (*StorageDisconnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageDisconnectResponse)
	err := c.cc.Invoke(ctx, StoragePlugin_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storagePluginClient) Get(ctx context.Context, in *StorageGetRequest, opts ...grpc.CallOption) (*StorageGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageGetResponse)
	err := c.cc.Invoke(ctx, StoragePlugin_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storagePluginClient) Set(ctx context.Context, in *StorageSetRequest, opts ...grpc.CallOption) (*StorageSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageSetResponse)
	err := c.cc.Invoke(ctx, StoragePlugin_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storagePluginClient) Delete(ctx context.Context, in *StorageDeleteRequest, opts ...grpc.CallOption) (*StorageDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageDeleteResponse)
	err := c.cc.Invoke(ctx, StoragePlugin_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storagePluginClient) List(ctx context.Context, in *StorageListRequest, opts ...grpc.CallOption) (*StorageListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageListResponse)
	err := c.cc.Invoke(ctx, StoragePlugin_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storagePluginClient) Query(ctx context.Context, in *StorageQueryRequest, opts ...grpc.CallOption) (*StorageQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageQueryResponse)
	err := c.cc.Invoke(ctx, StoragePlugin_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storagePluginClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, StoragePlugin_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoragePluginServer is the server API for StoragePlugin service.
// All implementations must embed UnimplementedStoragePluginServer
// for forward compatibility.
type StoragePluginServer interface {
	Info(context.Context, *Empty) (*PluginInfo, error)
	Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	Connect(context.Context, *StorageConnectRequest) (*StorageConnectResponse, error)
	Disconnect(context.Context, *StorageDisconnectRequest) (*StorageDisconnectResponse, error)
	Get(context.Context, *StorageGetRequest) (*StorageGetResponse, error)
	Set(context.Context, *StorageSetRequest) (*StorageSetResponse, error)
	Delete(context.Context, *StorageDeleteRequest) (*StorageDeleteResponse, error)
	List(context.Context, *StorageListRequest) (*StorageListResponse, error)
	Query(context.Context, *StorageQueryRequest) (*StorageQueryResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedStoragePluginServer()
}

// UnimplementedStoragePluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStoragePluginServer struct{}

func (UnimplementedStoragePluginServer) Info(context.Context, *Empty) (*PluginInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedStoragePluginServer) Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedStoragePluginServer) Connect(context.Context, *StorageConnectRequest) (*StorageConnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedStoragePluginServer) Disconnect(context.Context, *StorageDisconnectRequest) (*StorageDisconnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedStoragePluginServer) Get(context.Context, *StorageGetRequest) (*StorageGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedStoragePluginServer) Set(context.Context, *StorageSetRequest) (*StorageSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedStoragePluginServer) Delete(context.Context, *StorageDeleteRequest) (*StorageDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedStoragePluginServer) List(context.Context, *StorageListRequest) (*StorageListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedStoragePluginServer) Query(context.Context, *StorageQueryRequest) (*StorageQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedStoragePluginServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedStoragePluginServer) mustEmbedUnimplementedStoragePluginServer() {}
func (UnimplementedStoragePluginServer) testEmbeddedByValue()                       {}

// UnsafeStoragePluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoragePluginServer will
// result in compilation errors.
type UnsafeStoragePluginServer interface {
	mustEmbedUnimplementedStoragePluginServer()
}

func RegisterStoragePluginServer(s grpc.ServiceRegistrar, srv StoragePluginServer) {
	// If the following call panics, it indicates UnimplementedStoragePluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StoragePlugin_ServiceDesc, srv)
}

func _StoragePlugin_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoragePluginServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoragePlugin_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoragePluginServer).Info(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoragePlugin_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoragePluginServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoragePlugin_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoragePluginServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoragePlugin_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoragePluginServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoragePlugin_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoragePluginServer).Connect(ctx, req.(*StorageConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoragePlugin_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageDisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoragePluginServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoragePlugin_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoragePluginServer).Disconnect(ctx, req.(*StorageDisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoragePlugin_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoragePluginServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoragePlugin_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoragePluginServer).Get(ctx, req.(*StorageGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoragePlugin_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoragePluginServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoragePlugin_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoragePluginServer).Set(ctx, req.(*StorageSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoragePlugin_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoragePluginServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoragePlugin_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoragePluginServer).Delete(ctx, req.(*StorageDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoragePlugin_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoragePluginServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoragePlugin_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoragePluginServer).List(ctx, req.(*StorageListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoragePlugin_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoragePluginServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoragePlugin_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoragePluginServer).Query(ctx, req.(*StorageQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoragePlugin_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoragePluginServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoragePlugin_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoragePluginServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StoragePlugin_ServiceDesc is the grpc.ServiceDesc for StoragePlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StoragePlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "darkd.plugin.StoragePlugin",
	HandlerType: (*StoragePluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _StoragePlugin_Info_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _StoragePlugin_Configure_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _StoragePlugin_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _StoragePlugin_Disconnect_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _StoragePlugin_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _StoragePlugin_Set_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _StoragePlugin_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _StoragePlugin_List_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _StoragePlugin_Query_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _StoragePlugin_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/plugin/plugin.proto",
}

const (
	ReporterPlugin_Info_FullMethodName             = "/darkd.plugin.ReporterPlugin/Info"
	ReporterPlugin_Configure_FullMethodName        = "/darkd.plugin.ReporterPlugin/Configure"
	ReporterPlugin_SupportedFormats_FullMethodName = "/darkd.plugin.ReporterPlugin/SupportedFormats"
	ReporterPlugin_Generate_FullMethodName         = "/darkd.plugin.ReporterPlugin/Generate"
	ReporterPlugin_Health_FullMethodName           = "/darkd.plugin.ReporterPlugin/Health"
)

// ReporterPluginClient is the client API for ReporterPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReporterPluginClient interface {
	Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error)
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
	SupportedFormats(ctx context.Context, in *ReporterFormatsRequest, opts ...grpc.CallOption) (*ReporterFormatsResponse, error)
	Generate(ctx context.Context, in *ReporterGenerateRequest, opts ...grpc.CallOption) (*ReporterGenerateResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type reporterPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewReporterPluginClient(cc grpc.ClientConnInterface) ReporterPluginClient {
	return &reporterPluginClient{cc}
}

func (c *reporterPluginClient) Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginInfo)
	err := c.cc.Invoke(ctx, ReporterPlugin_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reporterPluginClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureResponse)
	err := c.cc.Invoke(ctx, ReporterPlugin_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reporterPluginClient) SupportedFormats(ctx context.Context, in *ReporterFormatsRequest, opts ...grpc.CallOption) (*ReporterFormatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReporterFormatsResponse)
	err := c.cc.Invoke(ctx, ReporterPlugin_SupportedFormats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reporterPluginClient) Generate(ctx context.Context, in *ReporterGenerateRequest, opts ...grpc.CallOption) (*ReporterGenerateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReporterGenerateResponse)
	err := c.cc.Invoke(ctx, ReporterPlugin_Generate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reporterPluginClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ReporterPlugin_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReporterPluginServer is the server API for ReporterPlugin service.
// All implementations must embed UnimplementedReporterPluginServer
// for forward compatibility.
type ReporterPluginServer interface {
	Info(context.Context, *Empty) (*PluginInfo, error)
	Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	SupportedFormats(context.Context, *ReporterFormatsRequest) (*ReporterFormatsResponse, error)
	Generate(context.Context, *ReporterGenerateRequest) (*ReporterGenerateResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedReporterPluginServer()
}

// UnimplementedReporterPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReporterPluginServer struct{}

func (UnimplementedReporterPluginServer) Info(context.Context, *Empty) (*PluginInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedReporterPluginServer) Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedReporterPluginServer) SupportedFormats(context.Context, *ReporterFormatsRequest) (*ReporterFormatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SupportedFormats not implemented")
}
func (UnimplementedReporterPluginServer) Generate(context.Context, *ReporterGenerateRequest) (*ReporterGenerateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedReporterPluginServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedReporterPluginServer) mustEmbedUnimplementedReporterPluginServer() {}
func (UnimplementedReporterPluginServer) testEmbeddedByValue()                        {}

// UnsafeReporterPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReporterPluginServer will
// result in compilation errors.
type UnsafeReporterPluginServer interface {
	mustEmbedUnimplementedReporterPluginServer()
}

func RegisterReporterPluginServer(s grpc.ServiceRegistrar, srv ReporterPluginServer) {
	// If the following call panics, it indicates UnimplementedReporterPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReporterPlugin_ServiceDesc, srv)
}

func _ReporterPlugin_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterPluginServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReporterPlugin_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterPluginServer).Info(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReporterPlugin_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterPluginServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReporterPlugin_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterPluginServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReporterPlugin_SupportedFormats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReporterFormatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterPluginServer).SupportedFormats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReporterPlugin_SupportedFormats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterPluginServer).SupportedFormats(ctx, req.(*ReporterFormatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReporterPlugin_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReporterGenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterPluginServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReporterPlugin_Generate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterPluginServer).Generate(ctx, req.(*ReporterGenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReporterPlugin_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterPluginServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReporterPlugin_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterPluginServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReporterPlugin_ServiceDesc is the grpc.ServiceDesc for ReporterPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReporterPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "darkd.plugin.ReporterPlugin",
	HandlerType: (*ReporterPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _ReporterPlugin_Info_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _ReporterPlugin_Configure_Handler,
		},
		{
			MethodName: "SupportedFormats",
			Handler:    _ReporterPlugin_SupportedFormats_Handler,
		},
		{
			MethodName: "Generate",
			Handler:    _ReporterPlugin_Generate_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _ReporterPlugin_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/plugin/plugin.proto",
}

const (
	CLIPlugin_Info_FullMethodName      = "/darkd.plugin.CLIPlugin/Info"
	CLIPlugin_Configure_FullMethodName = "/darkd.plugin.CLIPlugin/Configure"
	CLIPlugin_Commands_FullMethodName  = "/darkd.plugin.CLIPlugin/Commands"
	CLIPlugin_Execute_FullMethodName   = "/darkd.plugin.CLIPlugin/Execute"
	CLIPlugin_Health_FullMethodName    = "/darkd.plugin.CLIPlugin/Health"
)

// CLIPluginClient is the client API for CLIPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CLIPluginClient interface {
	Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error)
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
	Commands(ctx context.Context, in *CLICommandsRequest, opts ...grpc.CallOption) (*CLICommandsResponse, error)
	Execute(ctx context.Context, in *CLIExecuteRequest, opts ...grpc.CallOption) (*CLIExecuteResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type cLIPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewCLIPluginClient(cc grpc.ClientConnInterface) CLIPluginClient {
	return &cLIPluginClient{cc}
}

func (c *cLIPluginClient) Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginInfo)
	err := c.cc.Invoke(ctx, CLIPlugin_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIPluginClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureResponse)
	err := c.cc.Invoke(ctx, CLIPlugin_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIPluginClient) Commands(ctx context.Context, in *CLICommandsRequest, opts ...grpc.CallOption) (*CLICommandsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CLICommandsResponse)
	err := c.cc.Invoke(ctx, CLIPlugin_Commands_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIPluginClient) Execute(ctx context.Context, in *CLIExecuteRequest, opts ...grpc.CallOption) (*CLIExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CLIExecuteResponse)
	err := c.cc.Invoke(ctx, CLIPlugin_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cLIPluginClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, CLIPlugin_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CLIPluginServer is the server API for CLIPlugin service.
// All implementations must embed UnimplementedCLIPluginServer
// for forward compatibility.
type CLIPluginServer interface {
	Info(context.Context, *Empty) (*PluginInfo, error)
	Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	Commands(context.Context, *CLICommandsRequest) (*CLICommandsResponse, error)
	Execute(context.Context, *CLIExecuteRequest) (*CLIExecuteResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedCLIPluginServer()
}

// UnimplementedCLIPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCLIPluginServer struct{}

func (UnimplementedCLIPluginServer) Info(context.Context, *Empty) (*PluginInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedCLIPluginServer) Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedCLIPluginServer) Commands(context.Context, *CLICommandsRequest) (*CLICommandsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Commands not implemented")
}
func (UnimplementedCLIPluginServer) Execute(context.Context, *CLIExecuteRequest) (*CLIExecuteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedCLIPluginServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedCLIPluginServer) mustEmbedUnimplementedCLIPluginServer() {}
func (UnimplementedCLIPluginServer) testEmbeddedByValue()                   {}

// UnsafeCLIPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CLIPluginServer will
// result in compilation errors.
type UnsafeCLIPluginServer interface {
	mustEmbedUnimplementedCLIPluginServer()
}

func RegisterCLIPluginServer(s grpc.ServiceRegistrar, srv CLIPluginServer) {
	// If the following call panics, it indicates UnimplementedCLIPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CLIPlugin_ServiceDesc, srv)
}

func _CLIPlugin_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIPluginServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLIPlugin_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIPluginServer).Info(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLIPlugin_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIPluginServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLIPlugin_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIPluginServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLIPlugin_Commands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CLICommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIPluginServer).Commands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLIPlugin_Commands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIPluginServer).Commands(ctx, req.(*CLICommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLIPlugin_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CLIExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIPluginServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLIPlugin_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIPluginServer).Execute(ctx, req.(*CLIExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CLIPlugin_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CLIPluginServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CLIPlugin_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CLIPluginServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CLIPlugin_ServiceDesc is the grpc.ServiceDesc for CLIPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CLIPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "darkd.plugin.CLIPlugin",
	HandlerType: (*CLIPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _CLIPlugin_Info_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _CLIPlugin_Configure_Handler,
		},
		{
			MethodName: "Commands",
			Handler:    _CLIPlugin_Commands_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _CLIPlugin_Execute_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _CLIPlugin_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/plugin/plugin.proto",
}
