// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/plugin/plugin.proto

package plugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{0}
}

type PluginInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Author        string                 `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	License       string                 `protobuf:"bytes,6,opt,name=license,proto3" json:"license,omitempty"`
	Capabilities  []string               `protobuf:"bytes,7,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PluginInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PluginInfo) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *PluginInfo) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type PluginHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	LastCheckUnix int64                  `protobuf:"varint,3,opt,name=last_check_unix,json=lastCheckUnix,proto3" json:"last_check_unix,omitempty"`
	Metrics       map[string]string      `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginHealth) Reset() {
	*x = PluginHealth{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginHealth) ProtoMessage() {}

func (x *PluginHealth) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginHealth.ProtoReflect.Descriptor instead.
func (*PluginHealth) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *PluginHealth) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *PluginHealth) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PluginHealth) GetLastCheckUnix() int64 {
	if x != nil {
		return x.LastCheckUnix
	}
	return 0
}

func (x *PluginHealth) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type ConfigureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ConfigJson    []byte                 `protobuf:"bytes,2,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"` // For complex nested configs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigureRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ConfigureRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigureResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{5}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Health        *PluginHealth          `protobuf:"bytes,1,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *HealthResponse) GetHealth() *PluginHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

type ServiceStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceStartRequest) Reset() {
	*x = ServiceStartRequest{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStartRequest) ProtoMessage() {}

func (x *ServiceStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStartRequest.ProtoReflect.Descriptor instead.
func (*ServiceStartRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{7}
}

type ServiceStartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceStartResponse) Reset() {
	*x = ServiceStartResponse{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStartResponse) ProtoMessage() {}

func (x *ServiceStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStartResponse.ProtoReflect.Descriptor instead.
func (*ServiceStartResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *ServiceStartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ServiceStartResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ServiceStopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceStopRequest) Reset() {
	*x = ServiceStopRequest{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStopRequest) ProtoMessage() {}

func (x *ServiceStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStopRequest.ProtoReflect.Descriptor instead.
func (*ServiceStopRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{9}
}

type ServiceStopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceStopResponse) Reset() {
	*x = ServiceStopResponse{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStopResponse) ProtoMessage() {}

func (x *ServiceStopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStopResponse.ProtoReflect.Descriptor instead.
func (*ServiceStopResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *ServiceStopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ServiceStopResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ServiceExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	ParamsJson    []byte                 `protobuf:"bytes,2,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceExecuteRequest) Reset() {
	*x = ServiceExecuteRequest{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceExecuteRequest) ProtoMessage() {}

func (x *ServiceExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceExecuteRequest.ProtoReflect.Descriptor instead.
func (*ServiceExecuteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *ServiceExecuteRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ServiceExecuteRequest) GetParamsJson() []byte {
	if x != nil {
		return x.ParamsJson
	}
	return nil
}

type ServiceExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ResultJson    []byte                 `protobuf:"bytes,3,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceExecuteResponse) Reset() {
	*x = ServiceExecuteResponse{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceExecuteResponse) ProtoMessage() {}

func (x *ServiceExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceExecuteResponse.ProtoReflect.Descriptor instead.
func (*ServiceExecuteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *ServiceExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ServiceExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ServiceExecuteResponse) GetResultJson() []byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

type DataSourceConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataSourceConnectRequest) Reset() {
	*x = DataSourceConnectRequest{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataSourceConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSourceConnectRequest) ProtoMessage() {}

func (x *DataSourceConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSourceConnectRequest.ProtoReflect.Descriptor instead.
func (*DataSourceConnectRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{13}
}

type DataSourceConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataSourceConnectResponse) Reset() {
	*x = DataSourceConnectResponse{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataSourceConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSourceConnectResponse) ProtoMessage() {}

func (x *DataSourceConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSourceConnectResponse.ProtoReflect.Descriptor instead.
func (*DataSourceConnectResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *DataSourceConnectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DataSourceConnectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DataSourceDisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataSourceDisconnectRequest) Reset() {
	*x = DataSourceDisconnectRequest{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataSourceDisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSourceDisconnectRequest) ProtoMessage() {}

func (x *DataSourceDisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSourceDisconnectRequest.ProtoReflect.Descriptor instead.
func (*DataSourceDisconnectRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{15}
}

type DataSourceDisconnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataSourceDisconnectResponse) Reset() {
	*x = DataSourceDisconnectResponse{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataSourceDisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSourceDisconnectResponse) ProtoMessage() {}

func (x *DataSourceDisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSourceDisconnectResponse.ProtoReflect.Descriptor instead.
func (*DataSourceDisconnectResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *DataSourceDisconnectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DataSourceDisconnectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DataSourceQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	ParamsJson    []byte                 `protobuf:"bytes,2,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataSourceQueryRequest) Reset() {
	*x = DataSourceQueryRequest{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataSourceQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSourceQueryRequest) ProtoMessage() {}

func (x *DataSourceQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSourceQueryRequest.ProtoReflect.Descriptor instead.
func (*DataSourceQueryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *DataSourceQueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *DataSourceQueryRequest) GetParamsJson() []byte {
	if x != nil {
		return x.ParamsJson
	}
	return nil
}

type DataSourceQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ResultsJson   [][]byte               `protobuf:"bytes,3,rep,name=results_json,json=resultsJson,proto3" json:"results_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataSourceQueryResponse) Reset() {
	*x = DataSourceQueryResponse{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataSourceQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSourceQueryResponse) ProtoMessage() {}

func (x *DataSourceQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSourceQueryResponse.ProtoReflect.Descriptor instead.
func (*DataSourceQueryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *DataSourceQueryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DataSourceQueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DataSourceQueryResponse) GetResultsJson() [][]byte {
	if x != nil {
		return x.ResultsJson
	}
	return nil
}

type DataSourceSubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataSourceSubscribeRequest) Reset() {
	*x = DataSourceSubscribeRequest{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataSourceSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSourceSubscribeRequest) ProtoMessage() {}

func (x *DataSourceSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSourceSubscribeRequest.ProtoReflect.Descriptor instead.
func (*DataSourceSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *DataSourceSubscribeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type DataSourceSubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataJson      []byte                 `protobuf:"bytes,1,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataSourceSubscribeResponse) Reset() {
	*x = DataSourceSubscribeResponse{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataSourceSubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSourceSubscribeResponse) ProtoMessage() {}

func (x *DataSourceSubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSourceSubscribeResponse.ProtoReflect.Descriptor instead.
func (*DataSourceSubscribeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *DataSourceSubscribeResponse) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

type StorageConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageConnectRequest) Reset() {
	*x = StorageConnectRequest{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageConnectRequest) ProtoMessage() {}

func (x *StorageConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageConnectRequest.ProtoReflect.Descriptor instead.
func (*StorageConnectRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{21}
}

type StorageConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageConnectResponse) Reset() {
	*x = StorageConnectResponse{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageConnectResponse) ProtoMessage() {}

func (x *StorageConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageConnectResponse.ProtoReflect.Descriptor instead.
func (*StorageConnectResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *StorageConnectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StorageConnectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StorageDisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageDisconnectRequest) Reset() {
	*x = StorageDisconnectRequest{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageDisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageDisconnectRequest) ProtoMessage() {}

func (x *StorageDisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageDisconnectRequest.ProtoReflect.Descriptor instead.
func (*StorageDisconnectRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{23}
}

type StorageDisconnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageDisconnectResponse) Reset() {
	*x = StorageDisconnectResponse{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageDisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageDisconnectResponse) ProtoMessage() {}

func (x *StorageDisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageDisconnectResponse.ProtoReflect.Descriptor instead.
func (*StorageDisconnectResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{24}
}

func (x *StorageDisconnectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StorageDisconnectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StorageGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageGetRequest) Reset() {
	*x = StorageGetRequest{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageGetRequest) ProtoMessage() {}

func (x *StorageGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageGetRequest.ProtoReflect.Descriptor instead.
func (*StorageGetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{25}
}

func (x *StorageGetRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *StorageGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type StorageGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,4,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageGetResponse) Reset() {
	*x = StorageGetResponse{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageGetResponse) ProtoMessage() {}

func (x *StorageGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageGetResponse.ProtoReflect.Descriptor instead.
func (*StorageGetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{26}
}

func (x *StorageGetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StorageGetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StorageGetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *StorageGetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type StorageSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageSetRequest) Reset() {
	*x = StorageSetRequest{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageSetRequest) ProtoMessage() {}

func (x *StorageSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageSetRequest.ProtoReflect.Descriptor instead.
func (*StorageSetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{27}
}

func (x *StorageSetRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *StorageSetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StorageSetRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type StorageSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageSetResponse) Reset() {
	*x = StorageSetResponse{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageSetResponse) ProtoMessage() {}

func (x *StorageSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageSetResponse.ProtoReflect.Descriptor instead.
func (*StorageSetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{28}
}

func (x *StorageSetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StorageSetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StorageDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageDeleteRequest) Reset() {
	*x = StorageDeleteRequest{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageDeleteRequest) ProtoMessage() {}

func (x *StorageDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageDeleteRequest.ProtoReflect.Descriptor instead.
func (*StorageDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{29}
}

func (x *StorageDeleteRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *StorageDeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type StorageDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageDeleteResponse) Reset() {
	*x = StorageDeleteResponse{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageDeleteResponse) ProtoMessage() {}

func (x *StorageDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageDeleteResponse.ProtoReflect.Descriptor instead.
func (*StorageDeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{30}
}

func (x *StorageDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StorageDeleteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StorageListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageListRequest) Reset() {
	*x = StorageListRequest{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageListRequest) ProtoMessage() {}

func (x *StorageListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageListRequest.ProtoReflect.Descriptor instead.
func (*StorageListRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{31}
}

func (x *StorageListRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *StorageListRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type StorageListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Keys          []string               `protobuf:"bytes,3,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageListResponse) Reset() {
	*x = StorageListResponse{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageListResponse) ProtoMessage() {}

func (x *StorageListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageListResponse.ProtoReflect.Descriptor instead.
func (*StorageListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{32}
}

func (x *StorageListResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StorageListResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StorageListResponse) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type StorageQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	QueryJson     []byte                 `protobuf:"bytes,2,opt,name=query_json,json=queryJson,proto3" json:"query_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageQueryRequest) Reset() {
	*x = StorageQueryRequest{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageQueryRequest) ProtoMessage() {}

func (x *StorageQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageQueryRequest.ProtoReflect.Descriptor instead.
func (*StorageQueryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{33}
}

func (x *StorageQueryRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *StorageQueryRequest) GetQueryJson() []byte {
	if x != nil {
		return x.QueryJson
	}
	return nil
}

type StorageQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Results       [][]byte               `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageQueryResponse) Reset() {
	*x = StorageQueryResponse{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageQueryResponse) ProtoMessage() {}

func (x *StorageQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageQueryResponse.ProtoReflect.Descriptor instead.
func (*StorageQueryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{34}
}

func (x *StorageQueryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StorageQueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StorageQueryResponse) GetResults() [][]byte {
	if x != nil {
		return x.Results
	}
	return nil
}

type ReporterFormatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReporterFormatsRequest) Reset() {
	*x = ReporterFormatsRequest{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReporterFormatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReporterFormatsRequest) ProtoMessage() {}

func (x *ReporterFormatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReporterFormatsRequest.ProtoReflect.Descriptor instead.
func (*ReporterFormatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{35}
}

type ReporterFormatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Formats       []string               `protobuf:"bytes,1,rep,name=formats,proto3" json:"formats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReporterFormatsResponse) Reset() {
	*x = ReporterFormatsResponse{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReporterFormatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReporterFormatsResponse) ProtoMessage() {}

func (x *ReporterFormatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReporterFormatsResponse.ProtoReflect.Descriptor instead.
func (*ReporterFormatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{36}
}

func (x *ReporterFormatsResponse) GetFormats() []string {
	if x != nil {
		return x.Formats
	}
	return nil
}

type ReporterGenerateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        string                 `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	DataJson      []byte                 `protobuf:"bytes,2,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReporterGenerateRequest) Reset() {
	*x = ReporterGenerateRequest{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReporterGenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReporterGenerateRequest) ProtoMessage() {}

func (x *ReporterGenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReporterGenerateRequest.ProtoReflect.Descriptor instead.
func (*ReporterGenerateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{37}
}

func (x *ReporterGenerateRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ReporterGenerateRequest) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

type ReporterGenerateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Report        []byte                 `protobuf:"bytes,3,opt,name=report,proto3" json:"report,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReporterGenerateResponse) Reset() {
	*x = ReporterGenerateResponse{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReporterGenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReporterGenerateResponse) ProtoMessage() {}

func (x *ReporterGenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReporterGenerateResponse.ProtoReflect.Descriptor instead.
func (*ReporterGenerateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{38}
}

func (x *ReporterGenerateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReporterGenerateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReporterGenerateResponse) GetReport() []byte {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *ReporterGenerateResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type CLIFlag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Shorthand     string                 `protobuf:"bytes,2,opt,name=shorthand,proto3" json:"shorthand,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	DefaultValue  string                 `protobuf:"bytes,5,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Required      bool                   `protobuf:"varint,6,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CLIFlag) Reset() {
	*x = CLIFlag{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CLIFlag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CLIFlag) ProtoMessage() {}

func (x *CLIFlag) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CLIFlag.ProtoReflect.Descriptor instead.
func (*CLIFlag) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{39}
}

func (x *CLIFlag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CLIFlag) GetShorthand() string {
	if x != nil {
		return x.Shorthand
	}
	return ""
}

func (x *CLIFlag) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CLIFlag) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CLIFlag) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *CLIFlag) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

type CLICommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Usage         string                 `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	Flags         []*CLIFlag             `protobuf:"bytes,4,rep,name=flags,proto3" json:"flags,omitempty"`
	Subcommands   []*CLICommand          `protobuf:"bytes,5,rep,name=subcommands,proto3" json:"subcommands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CLICommand) Reset() {
	*x = CLICommand{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CLICommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CLICommand) ProtoMessage() {}

func (x *CLICommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CLICommand.ProtoReflect.Descriptor instead.
func (*CLICommand) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{40}
}

func (x *CLICommand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CLICommand) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CLICommand) GetUsage() string {
	if x != nil {
		return x.Usage
	}
	return ""
}

func (x *CLICommand) GetFlags() []*CLIFlag {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *CLICommand) GetSubcommands() []*CLICommand {
	if x != nil {
		return x.Subcommands
	}
	return nil
}

type CLICommandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CLICommandsRequest) Reset() {
	*x = CLICommandsRequest{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CLICommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CLICommandsRequest) ProtoMessage() {}

func (x *CLICommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CLICommandsRequest.ProtoReflect.Descriptor instead.
func (*CLICommandsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{41}
}

type CLICommandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*CLICommand          `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CLICommandsResponse) Reset() {
	*x = CLICommandsResponse{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CLICommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CLICommandsResponse) ProtoMessage() {}

func (x *CLICommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CLICommandsResponse.ProtoReflect.Descriptor instead.
func (*CLICommandsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{42}
}

func (x *CLICommandsResponse) GetCommands() []*CLICommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

type CLIExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Flags         map[string]string      `protobuf:"bytes,3,rep,name=flags,proto3" json:"flags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FlagsJson     []byte                 `protobuf:"bytes,4,opt,name=flags_json,json=flagsJson,proto3" json:"flags_json,omitempty"` // For complex flag values
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CLIExecuteRequest) Reset() {
	*x = CLIExecuteRequest{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CLIExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CLIExecuteRequest) ProtoMessage() {}

func (x *CLIExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CLIExecuteRequest.ProtoReflect.Descriptor instead.
func (*CLIExecuteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{43}
}

func (x *CLIExecuteRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CLIExecuteRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CLIExecuteRequest) GetFlags() map[string]string {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *CLIExecuteRequest) GetFlagsJson() []byte {
	if x != nil {
		return x.FlagsJson
	}
	return nil
}

type CLIExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CLIExecuteResponse) Reset() {
	*x = CLIExecuteResponse{}
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CLIExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CLIExecuteResponse) ProtoMessage() {}

func (x *CLIExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plugin_plugin_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CLIExecuteResponse.ProtoReflect.Descriptor instead.
func (*CLIExecuteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plugin_plugin_proto_rawDescGZIP(), []int{44}
}

func (x *CLIExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CLIExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CLIExecuteResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *CLIExecuteResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

var File_api_proto_plugin_plugin_proto protoreflect.FileDescriptor

const file_api_proto_plugin_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/plugin/plugin.proto\x12\fdarkd.plugin\"\a\n" +
	"\x05Empty\"\xc6\x01\n" +
	"\n" +
	"PluginInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12\x18\n" +
	"\alicense\x18\x06 \x01(\tR\alicense\x12\"\n" +
	"\fcapabilities\x18\a \x03(\tR\fcapabilities\"\xe5\x01\n" +
	"\fPluginHealth\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12&\n" +
	"\x0flast_check_unix\x18\x03 \x01(\x03R\rlastCheckUnix\x12A\n" +
	"\ametrics\x18\x04 \x03(\v2'.darkd.plugin.PluginHealth.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb2\x01\n" +
	"\x10ConfigureRequest\x12B\n" +
	"\x06config\x18\x01 \x03(\v2*.darkd.plugin.ConfigureRequest.ConfigEntryR\x06config\x12\x1f\n" +
	"\vconfig_json\x18\x02 \x01(\fR\n" +
	"configJson\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\x11ConfigureResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x0f\n" +
	"\rHealthRequest\"D\n" +
	"\x0eHealthResponse\x122\n" +
	"\x06health\x18\x01 \x01(\v2\x1a.darkd.plugin.PluginHealthR\x06health\"\x15\n" +
	"\x13ServiceStartRequest\"F\n" +
	"\x14ServiceStartResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x14\n" +
	"\x12ServiceStopRequest\"E\n" +
	"\x13ServiceStopResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"P\n" +
	"\x15ServiceExecuteRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1f\n" +
	"\vparams_json\x18\x02 \x01(\fR\n" +
	"paramsJson\"i\n" +
	"\x16ServiceExecuteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\vresult_json\x18\x03 \x01(\fR\n" +
	"resultJson\"\x1a\n" +
	"\x18DataSourceConnectRequest\"K\n" +
	"\x19DataSourceConnectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x1d\n" +
	"\x1bDataSourceDisconnectRequest\"N\n" +
	"\x1cDataSourceDisconnectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"O\n" +
	"\x16DataSourceQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1f\n" +
	"\vparams_json\x18\x02 \x01(\fR\n" +
	"paramsJson\"l\n" +
	"\x17DataSourceQueryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12!\n" +
	"\fresults_json\x18\x03 \x03(\fR\vresultsJson\"2\n" +
	"\x1aDataSourceSubscribeRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\":\n" +
	"\x1bDataSourceSubscribeResponse\x12\x1b\n" +
	"\tdata_json\x18\x01 \x01(\fR\bdataJson\"\x17\n" +
	"\x15StorageConnectRequest\"H\n" +
	"\x16StorageConnectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x1a\n" +
	"\x18StorageDisconnectRequest\"K\n" +
	"\x19StorageDisconnectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"E\n" +
	"\x11StorageGetRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"p\n" +
	"\x12StorageGetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x04 \x01(\bR\x05found\"[\n" +
	"\x11StorageSetRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"D\n" +
	"\x12StorageSetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"H\n" +
	"\x14StorageDeleteRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"G\n" +
	"\x15StorageDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"L\n" +
	"\x12StorageListRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\"Y\n" +
	"\x13StorageListResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x12\n" +
	"\x04keys\x18\x03 \x03(\tR\x04keys\"T\n" +
	"\x13StorageQueryRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x1d\n" +
	"\n" +
	"query_json\x18\x02 \x01(\fR\tqueryJson\"`\n" +
	"\x14StorageQueryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\aresults\x18\x03 \x03(\fR\aresults\"\x18\n" +
	"\x16ReporterFormatsRequest\"3\n" +
	"\x17ReporterFormatsResponse\x12\x18\n" +
	"\aformats\x18\x01 \x03(\tR\aformats\"N\n" +
	"\x17ReporterGenerateRequest\x12\x16\n" +
	"\x06format\x18\x01 \x01(\tR\x06format\x12\x1b\n" +
	"\tdata_json\x18\x02 \x01(\fR\bdataJson\"\x85\x01\n" +
	"\x18ReporterGenerateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x16\n" +
	"\x06report\x18\x03 \x01(\fR\x06report\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\"\xb2\x01\n" +
	"\aCLIFlag\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tshorthand\x18\x02 \x01(\tR\tshorthand\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12#\n" +
	"\rdefault_value\x18\x05 \x01(\tR\fdefaultValue\x12\x1a\n" +
	"\brequired\x18\x06 \x01(\bR\brequired\"\xc1\x01\n" +
	"\n" +
	"CLICommand\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05usage\x18\x03 \x01(\tR\x05usage\x12+\n" +
	"\x05flags\x18\x04 \x03(\v2\x15.darkd.plugin.CLIFlagR\x05flags\x12:\n" +
	"\vsubcommands\x18\x05 \x03(\v2\x18.darkd.plugin.CLICommandR\vsubcommands\"\x14\n" +
	"\x12CLICommandsRequest\"K\n" +
	"\x13CLICommandsResponse\x124\n" +
	"\bcommands\x18\x01 \x03(\v2\x18.darkd.plugin.CLICommandR\bcommands\"\xdc\x01\n" +
	"\x11CLIExecuteRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12@\n" +
	"\x05flags\x18\x03 \x03(\v2*.darkd.plugin.CLIExecuteRequest.FlagsEntryR\x05flags\x12\x1d\n" +
	"\n" +
	"flags_json\x18\x04 \x01(\fR\tflagsJson\x1a8\n" +
	"\n" +
	"FlagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"y\n" +
	"\x12CLIExecuteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode2\xcc\x03\n" +
	"\rServicePlugin\x125\n" +
	"\x04Info\x12\x13.darkd.plugin.Empty\x1a\x18.darkd.plugin.PluginInfo\x12L\n" +
	"\tConfigure\x12\x1e.darkd.plugin.ConfigureRequest\x1a\x1f.darkd.plugin.ConfigureResponse\x12N\n" +
	"\x05Start\x12!.darkd.plugin.ServiceStartRequest\x1a\".darkd.plugin.ServiceStartResponse\x12K\n" +
	"\x04Stop\x12 .darkd.plugin.ServiceStopRequest\x1a!.darkd.plugin.ServiceStopResponse\x12C\n" +
	"\x06Health\x12\x1b.darkd.plugin.HealthRequest\x1a\x1c.darkd.plugin.HealthResponse\x12T\n" +
	"\aExecute\x12#.darkd.plugin.ServiceExecuteRequest\x1a$.darkd.plugin.ServiceExecuteResponse2\xd7\x04\n" +
	"\x10DataSourcePlugin\x125\n" +
	"\x04Info\x12\x13.darkd.plugin.Empty\x1a\x18.darkd.plugin.PluginInfo\x12L\n" +
	"\tConfigure\x12\x1e.darkd.plugin.ConfigureRequest\x1a\x1f.darkd.plugin.ConfigureResponse\x12Z\n" +
	"\aConnect\x12&.darkd.plugin.DataSourceConnectRequest\x1a'.darkd.plugin.DataSourceConnectResponse\x12c\n" +
	"\n" +
	"Disconnect\x12).darkd.plugin.DataSourceDisconnectRequest\x1a*.darkd.plugin.DataSourceDisconnectResponse\x12T\n" +
	"\x05Query\x12$.darkd.plugin.DataSourceQueryRequest\x1a%.darkd.plugin.DataSourceQueryResponse\x12b\n" +
	"\tSubscribe\x12(.darkd.plugin.DataSourceSubscribeRequest\x1a).darkd.plugin.DataSourceSubscribeResponse0\x01\x12C\n" +
	"\x06Health\x12\x1b.darkd.plugin.HealthRequest\x1a\x1c.darkd.plugin.HealthResponse2\x92\x06\n" +
	"\rStoragePlugin\x125\n" +
	"\x04Info\x12\x13.darkd.plugin.Empty\x1a\x18.darkd.plugin.PluginInfo\x12L\n" +
	"\tConfigure\x12\x1e.darkd.plugin.ConfigureRequest\x1a\x1f.darkd.plugin.ConfigureResponse\x12T\n" +
	"\aConnect\x12#.darkd.plugin.StorageConnectRequest\x1a$.darkd.plugin.StorageConnectResponse\x12]\n" +
	"\n" +
	"Disconnect\x12&.darkd.plugin.StorageDisconnectRequest\x1a'.darkd.plugin.StorageDisconnectResponse\x12H\n" +
	"\x03Get\x12\x1f.darkd.plugin.StorageGetRequest\x1a .darkd.plugin.StorageGetResponse\x12H\n" +
	"\x03Set\x12\x1f.darkd.plugin.StorageSetRequest\x1a .darkd.plugin.StorageSetResponse\x12Q\n" +
	"\x06Delete\x12\".darkd.plugin.StorageDeleteRequest\x1a#.darkd.plugin.StorageDeleteResponse\x12K\n" +
	"\x04List\x12 .darkd.plugin.StorageListRequest\x1a!.darkd.plugin.StorageListResponse\x12N\n" +
	"\x05Query\x12!.darkd.plugin.StorageQueryRequest\x1a\".darkd.plugin.StorageQueryResponse\x12C\n" +
	"\x06Health\x12\x1b.darkd.plugin.HealthRequest\x1a\x1c.darkd.plugin.HealthResponse2\x96\x03\n" +
	"\x0eReporterPlugin\x125\n" +
	"\x04Info\x12\x13.darkd.plugin.Empty\x1a\x18.darkd.plugin.PluginInfo\x12L\n" +
	"\tConfigure\x12\x1e.darkd.plugin.ConfigureRequest\x1a\x1f.darkd.plugin.ConfigureResponse\x12_\n" +
	"\x10SupportedFormats\x12$.darkd.plugin.ReporterFormatsRequest\x1a%.darkd.plugin.ReporterFormatsResponse\x12Y\n" +
	"\bGenerate\x12%.darkd.plugin.ReporterGenerateRequest\x1a&.darkd.plugin.ReporterGenerateResponse\x12C\n" +
	"\x06Health\x12\x1b.darkd.plugin.HealthRequest\x1a\x1c.darkd.plugin.HealthResponse2\xf4\x02\n" +
	"\tCLIPlugin\x125\n" +
	"\x04Info\x12\x13.darkd.plugin.Empty\x1a\x18.darkd.plugin.PluginInfo\x12L\n" +
	"\tConfigure\x12\x1e.darkd.plugin.ConfigureRequest\x1a\x1f.darkd.plugin.ConfigureResponse\x12O\n" +
	"\bCommands\x12 .darkd.plugin.CLICommandsRequest\x1a!.darkd.plugin.CLICommandsResponse\x12L\n" +
	"\aExecute\x12\x1f.darkd.plugin.CLIExecuteRequest\x1a .darkd.plugin.CLIExecuteResponse\x12C\n" +
	"\x06Health\x12\x1b.darkd.plugin.HealthRequest\x1a\x1c.darkd.plugin.HealthResponseB:Z8github.com/afterdarksys/afterdark-darkd/api/proto/pluginb\x06proto3"

var (
	file_api_proto_plugin_plugin_proto_rawDescOnce sync.Once
	file_api_proto_plugin_plugin_proto_rawDescData []byte
)

func file_api_proto_plugin_plugin_proto_rawDescGZIP() []byte {
	file_api_proto_plugin_plugin_proto_rawDescOnce.Do(func() {
		file_api_proto_plugin_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_plugin_plugin_proto_rawDesc), len(file_api_proto_plugin_plugin_proto_rawDesc)))
	})
	return file_api_proto_plugin_plugin_proto_rawDescData
}

var file_api_proto_plugin_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 48)
var file_api_proto_plugin_plugin_proto_goTypes = []any{
	(*Empty)(nil),                        // 0: darkd.plugin.Empty
	(*PluginInfo)(nil),                   // 1: darkd.plugin.PluginInfo
	(*PluginHealth)(nil),                 // 2: darkd.plugin.PluginHealth
	(*ConfigureRequest)(nil),             // 3: darkd.plugin.ConfigureRequest
	(*ConfigureResponse)(nil),            // 4: darkd.plugin.ConfigureResponse
	(*HealthRequest)(nil),                // 5: darkd.plugin.HealthRequest
	(*HealthResponse)(nil),               // 6: darkd.plugin.HealthResponse
	(*ServiceStartRequest)(nil),          // 7: darkd.plugin.ServiceStartRequest
	(*ServiceStartResponse)(nil),         // 8: darkd.plugin.ServiceStartResponse
	(*ServiceStopRequest)(nil),           // 9: darkd.plugin.ServiceStopRequest
	(*ServiceStopResponse)(nil),          // 10: darkd.plugin.ServiceStopResponse
	(*ServiceExecuteRequest)(nil),        // 11: darkd.plugin.ServiceExecuteRequest
	(*ServiceExecuteResponse)(nil),       // 12: darkd.plugin.ServiceExecuteResponse
	(*DataSourceConnectRequest)(nil),     // 13: darkd.plugin.DataSourceConnectRequest
	(*DataSourceConnectResponse)(nil),    // 14: darkd.plugin.DataSourceConnectResponse
	(*DataSourceDisconnectRequest)(nil),  // 15: darkd.plugin.DataSourceDisconnectRequest
	(*DataSourceDisconnectResponse)(nil), // 16: darkd.plugin.DataSourceDisconnectResponse
	(*DataSourceQueryRequest)(nil),       // 17: darkd.plugin.DataSourceQueryRequest
	(*DataSourceQueryResponse)(nil),      // 18: darkd.plugin.DataSourceQueryResponse
	(*DataSourceSubscribeRequest)(nil),   // 19: darkd.plugin.DataSourceSubscribeRequest
	(*DataSourceSubscribeResponse)(nil),  // 20: darkd.plugin.DataSourceSubscribeResponse
	(*StorageConnectRequest)(nil),        // 21: darkd.plugin.StorageConnectRequest
	(*StorageConnectResponse)(nil),       // 22: darkd.plugin.StorageConnectResponse
	(*StorageDisconnectRequest)(nil),     // 23: darkd.plugin.StorageDisconnectRequest
	(*StorageDisconnectResponse)(nil),    // 24: darkd.plugin.StorageDisconnectResponse
	(*StorageGetRequest)(nil),            // 25: darkd.plugin.StorageGetRequest
	(*StorageGetResponse)(nil),           // 26: darkd.plugin.StorageGetResponse
	(*StorageSetRequest)(nil),            // 27: darkd.plugin.StorageSetRequest
	(*StorageSetResponse)(nil),           // 28: darkd.plugin.StorageSetResponse
	(*StorageDeleteRequest)(nil),         // 29: darkd.plugin.StorageDeleteRequest
	(*StorageDeleteResponse)(nil),        // 30: darkd.plugin.StorageDeleteResponse
	(*StorageListRequest)(nil),           // 31: darkd.plugin.StorageListRequest
	(*StorageListResponse)(nil),          // 32: darkd.plugin.StorageListResponse
	(*StorageQueryRequest)(nil),          // 33: darkd.plugin.StorageQueryRequest
	(*StorageQueryResponse)(nil),         // 34: darkd.plugin.StorageQueryResponse
	(*ReporterFormatsRequest)(nil),       // 35: darkd.plugin.ReporterFormatsRequest
	(*ReporterFormatsResponse)(nil),      // 36: darkd.plugin.ReporterFormatsResponse
	(*ReporterGenerateRequest)(nil),      // 37: darkd.plugin.ReporterGenerateRequest
	(*ReporterGenerateResponse)(nil),     // 38: darkd.plugin.ReporterGenerateResponse
	(*CLIFlag)(nil),                      // 39: darkd.plugin.CLIFlag
	(*CLICommand)(nil),                   // 40: darkd.plugin.CLICommand
	(*CLICommandsRequest)(nil),           // 41: darkd.plugin.CLICommandsRequest
	(*CLICommandsResponse)(nil),          // 42: darkd.plugin.CLICommandsResponse
	(*CLIExecuteRequest)(nil),            // 43: darkd.plugin.CLIExecuteRequest
	(*CLIExecuteResponse)(nil),           // 44: darkd.plugin.CLIExecuteResponse
	nil,                                  // 45: darkd.plugin.PluginHealth.MetricsEntry
	nil,                                  // 46: darkd.plugin.ConfigureRequest.ConfigEntry
	nil,                                  // 47: darkd.plugin.CLIExecuteRequest.FlagsEntry
}
var file_api_proto_plugin_plugin_proto_depIdxs = []int32{
	45, // 0: darkd.plugin.PluginHealth.metrics:type_name -> darkd.plugin.PluginHealth.MetricsEntry
	46, // 1: darkd.plugin.ConfigureRequest.config:type_name -> darkd.plugin.ConfigureRequest.ConfigEntry
	2,  // 2: darkd.plugin.HealthResponse.health:type_name -> darkd.plugin.PluginHealth
	39, // 3: darkd.plugin.CLICommand.flags:type_name -> darkd.plugin.CLIFlag
	40, // 4: darkd.plugin.CLICommand.subcommands:type_name -> darkd.plugin.CLICommand
	40, // 5: darkd.plugin.CLICommandsResponse.commands:type_name -> darkd.plugin.CLICommand
	47, // 6: darkd.plugin.CLIExecuteRequest.flags:type_name -> darkd.plugin.CLIExecuteRequest.FlagsEntry
	0,  // 7: darkd.plugin.ServicePlugin.Info:input_type -> darkd.plugin.Empty
	3,  // 8: darkd.plugin.ServicePlugin.Configure:input_type -> darkd.plugin.ConfigureRequest
	7,  // 9: darkd.plugin.ServicePlugin.Start:input_type -> darkd.plugin.ServiceStartRequest
	9,  // 10: darkd.plugin.ServicePlugin.Stop:input_type -> darkd.plugin.ServiceStopRequest
	5,  // 11: darkd.plugin.ServicePlugin.Health:input_type -> darkd.plugin.HealthRequest
	11, // 12: darkd.plugin.ServicePlugin.Execute:input_type -> darkd.plugin.ServiceExecuteRequest
	0,  // 13: darkd.plugin.DataSourcePlugin.Info:input_type -> darkd.plugin.Empty
	3,  // 14: darkd.plugin.DataSourcePlugin.Configure:input_type -> darkd.plugin.ConfigureRequest
	13, // 15: darkd.plugin.DataSourcePlugin.Connect:input_type -> darkd.plugin.DataSourceConnectRequest
	15, // 16: darkd.plugin.DataSourcePlugin.Disconnect:input_type -> darkd.plugin.DataSourceDisconnectRequest
	17, // 17: darkd.plugin.DataSourcePlugin.Query:input_type -> darkd.plugin.DataSourceQueryRequest
	19, // 18: darkd.plugin.DataSourcePlugin.Subscribe:input_type -> darkd.plugin.DataSourceSubscribeRequest
	5,  // 19: darkd.plugin.DataSourcePlugin.Health:input_type -> darkd.plugin.HealthRequest
	0,  // 20: darkd.plugin.StoragePlugin.Info:input_type -> darkd.plugin.Empty
	3,  // 21: darkd.plugin.StoragePlugin.Configure:input_type -> darkd.plugin.ConfigureRequest
	21, // 22: darkd.plugin.StoragePlugin.Connect:input_type -> darkd.plugin.StorageConnectRequest
	23, // 23: darkd.plugin.StoragePlugin.Disconnect:input_type -> darkd.plugin.StorageDisconnectRequest
	25, // 24: darkd.plugin.StoragePlugin.Get:input_type -> darkd.plugin.StorageGetRequest
	27, // 25: darkd.plugin.StoragePlugin.Set:input_type -> darkd.plugin.StorageSetRequest
	29, // 26: darkd.plugin.StoragePlugin.Delete:input_type -> darkd.plugin.StorageDeleteRequest
	31, // 27: darkd.plugin.StoragePlugin.List:input_type -> darkd.plugin.StorageListRequest
	33, // 28: darkd.plugin.StoragePlugin.Query:input_type -> darkd.plugin.StorageQueryRequest
	5,  // 29: darkd.plugin.StoragePlugin.Health:input_type -> darkd.plugin.HealthRequest
	0,  // 30: darkd.plugin.ReporterPlugin.Info:input_type -> darkd.plugin.Empty
	3,  // 31: darkd.plugin.ReporterPlugin.Configure:input_type -> darkd.plugin.ConfigureRequest
	35, // 32: darkd.plugin.ReporterPlugin.SupportedFormats:input_type -> darkd.plugin.ReporterFormatsRequest
	37, // 33: darkd.plugin.ReporterPlugin.Generate:input_type -> darkd.plugin.ReporterGenerateRequest
	5,  // 34: darkd.plugin.ReporterPlugin.Health:input_type -> darkd.plugin.HealthRequest
	0,  // 35: darkd.plugin.CLIPlugin.Info:input_type -> darkd.plugin.Empty
	3,  // 36: darkd.plugin.CLIPlugin.Configure:input_type -> darkd.plugin.ConfigureRequest
	41, // 37: darkd.plugin.CLIPlugin.Commands:input_type -> darkd.plugin.CLICommandsRequest
	43, // 38: darkd.plugin.CLIPlugin.Execute:input_type -> darkd.plugin.CLIExecuteRequest
	5,  // 39: darkd.plugin.CLIPlugin.Health:input_type -> darkd.plugin.HealthRequest
	1,  // 40: darkd.plugin.ServicePlugin.Info:output_type -> darkd.plugin.PluginInfo
	4,  // 41: darkd.plugin.ServicePlugin.Configure:output_type -> darkd.plugin.ConfigureResponse
	8,  // 42: darkd.plugin.ServicePlugin.Start:output_type -> darkd.plugin.ServiceStartResponse
	10, // 43: darkd.plugin.ServicePlugin.Stop:output_type -> darkd.plugin.ServiceStopResponse
	6,  // 44: darkd.plugin.ServicePlugin.Health:output_type -> darkd.plugin.HealthResponse
	12, // 45: darkd.plugin.ServicePlugin.Execute:output_type -> darkd.plugin.ServiceExecuteResponse
	1,  // 46: darkd.plugin.DataSourcePlugin.Info:output_type -> darkd.plugin.PluginInfo
	4,  // 47: darkd.plugin.DataSourcePlugin.Configure:output_type -> darkd.plugin.ConfigureResponse
	14, // 48: darkd.plugin.DataSourcePlugin.Connect:output_type -> darkd.plugin.DataSourceConnectResponse
	16, // 49: darkd.plugin.DataSourcePlugin.Disconnect:output_type -> darkd.plugin.DataSourceDisconnectResponse
	18, // 50: darkd.plugin.DataSourcePlugin.Query:output_type -> darkd.plugin.DataSourceQueryResponse
	20, // 51: darkd.plugin.DataSourcePlugin.Subscribe:output_type -> darkd.plugin.DataSourceSubscribeResponse
	6,  // 52: darkd.plugin.DataSourcePlugin.Health:output_type -> darkd.plugin.HealthResponse
	1,  // 53: darkd.plugin.StoragePlugin.Info:output_type -> darkd.plugin.PluginInfo
	4,  // 54: darkd.plugin.StoragePlugin.Configure:output_type -> darkd.plugin.ConfigureResponse
	22, // 55: darkd.plugin.StoragePlugin.Connect:output_type -> darkd.plugin.StorageConnectResponse
	24, // 56: darkd.plugin.StoragePlugin.Disconnect:output_type -> darkd.plugin.StorageDisconnectResponse
	26, // 57: darkd.plugin.StoragePlugin.Get:output_type -> darkd.plugin.StorageGetResponse
	28, // 58: darkd.plugin.StoragePlugin.Set:output_type -> darkd.plugin.StorageSetResponse
	30, // 59: darkd.plugin.StoragePlugin.Delete:output_type -> darkd.plugin.StorageDeleteResponse
	32, // 60: darkd.plugin.StoragePlugin.List:output_type -> darkd.plugin.StorageListResponse
	34, // 61: darkd.plugin.StoragePlugin.Query:output_type -> darkd.plugin.StorageQueryResponse
	6,  // 62: darkd.plugin.StoragePlugin.Health:output_type -> darkd.plugin.HealthResponse
	1,  // 63: darkd.plugin.ReporterPlugin.Info:output_type -> darkd.plugin.PluginInfo
	4,  // 64: darkd.plugin.ReporterPlugin.Configure:output_type -> darkd.plugin.ConfigureResponse
	36, // 65: darkd.plugin.ReporterPlugin.SupportedFormats:output_type -> darkd.plugin.ReporterFormatsResponse
	38, // 66: darkd.plugin.ReporterPlugin.Generate:output_type -> darkd.plugin.ReporterGenerateResponse
	6,  // 67: darkd.plugin.ReporterPlugin.Health:output_type -> darkd.plugin.HealthResponse
	1,  // 68: darkd.plugin.CLIPlugin.Info:output_type -> darkd.plugin.PluginInfo
	4,  // 69: darkd.plugin.CLIPlugin.Configure:output_type -> darkd.plugin.ConfigureResponse
	42, // 70: darkd.plugin.CLIPlugin.Commands:output_type -> darkd.plugin.CLICommandsResponse
	44, // 71: darkd.plugin.CLIPlugin.Execute:output_type -> darkd.plugin.CLIExecuteResponse
	6,  // 72: darkd.plugin.CLIPlugin.Health:output_type -> darkd.plugin.HealthResponse
	40, // [40:73] is the sub-list for method output_type
	7,  // [7:40] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_plugin_plugin_proto_init() }
func file_api_proto_plugin_plugin_proto_init() {
	if File_api_proto_plugin_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_plugin_plugin_proto_rawDesc), len(file_api_proto_plugin_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   48,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_api_proto_plugin_plugin_proto_goTypes,
		DependencyIndexes: file_api_proto_plugin_plugin_proto_depIdxs,
		MessageInfos:      file_api_proto_plugin_plugin_proto_msgTypes,
	}.Build()
	File_api_proto_plugin_plugin_proto = out.File
	file_api_proto_plugin_plugin_proto_goTypes = nil
	file_api_proto_plugin_plugin_proto_depIdxs = nil
}
