// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.36.1
// source: api/proto/ipc/control.proto

package ipc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ControlStopRequest carries a signed stop or upgrade token, produced offline
// by `afterdark-darkdadm control sign-stop`. At most 4096 bytes are accepted.
type ControlStopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         []byte                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlStopRequest) Reset() {
	*x = ControlStopRequest{}
	mi := &file_api_proto_ipc_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlStopRequest) ProtoMessage() {}

func (x *ControlStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ipc_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlStopRequest.ProtoReflect.Descriptor instead.
func (*ControlStopRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_ipc_control_proto_rawDescGZIP(), []int{0}
}

func (x *ControlStopRequest) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

// ControlStopResponse never echoes the token or its nonce.
type ControlStopResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Action         string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	KeyFingerprint string                 `protobuf:"bytes,2,opt,name=key_fingerprint,json=keyFingerprint,proto3" json:"key_fingerprint,omitempty"`
	WindowSeconds  int64                  `protobuf:"varint,3,opt,name=window_seconds,json=windowSeconds,proto3" json:"window_seconds,omitempty"`
	Message        string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ControlStopResponse) Reset() {
	*x = ControlStopResponse{}
	mi := &file_api_proto_ipc_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlStopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlStopResponse) ProtoMessage() {}

func (x *ControlStopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ipc_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlStopResponse.ProtoReflect.Descriptor instead.
func (*ControlStopResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_ipc_control_proto_rawDescGZIP(), []int{1}
}

func (x *ControlStopResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ControlStopResponse) GetKeyFingerprint() string {
	if x != nil {
		return x.KeyFingerprint
	}
	return ""
}

func (x *ControlStopResponse) GetWindowSeconds() int64 {
	if x != nil {
		return x.WindowSeconds
	}
	return 0
}

func (x *ControlStopResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_ipc_control_proto protoreflect.FileDescriptor

const file_api_proto_ipc_control_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/ipc/control.proto\x12\x03ipc\"*\n" +
	"\x12ControlStopRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\fR\x05token\"\x97\x01\n" +
	"\x13ControlStopResponse\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12'\n" +
	"\x0fkey_fingerprint\x18\x02 \x01(\tR\x0ekeyFingerprint\x12%\n" +
	"\x0ewindow_seconds\x18\x03 \x01(\x03R\rwindowSeconds\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage2K\n" +
	"\x0eControlService\x129\n" +
	"\x04Stop\x12\x17.ipc.ControlStopRequest\x1a\x18.ipc.ControlStopResponseB7Z5github.com/afterdarksys/afterdark-darkd/api/proto/ipcb\x06proto3"

var (
	file_api_proto_ipc_control_proto_rawDescOnce sync.Once
	file_api_proto_ipc_control_proto_rawDescData []byte
)

func file_api_proto_ipc_control_proto_rawDescGZIP() []byte {
	file_api_proto_ipc_control_proto_rawDescOnce.Do(func() {
		file_api_proto_ipc_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_ipc_control_proto_rawDesc), len(file_api_proto_ipc_control_proto_rawDesc)))
	})
	return file_api_proto_ipc_control_proto_rawDescData
}

var file_api_proto_ipc_control_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_ipc_control_proto_goTypes = []any{
	(*ControlStopRequest)(nil),  // 0: ipc.ControlStopRequest
	(*ControlStopResponse)(nil), // 1: ipc.ControlStopResponse
}
var file_api_proto_ipc_control_proto_depIdxs = []int32{
	0, // 0: ipc.ControlService.Stop:input_type -> ipc.ControlStopRequest
	1, // 1: ipc.ControlService.Stop:output_type -> ipc.ControlStopResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_ipc_control_proto_init() }
func file_api_proto_ipc_control_proto_init() {
	if File_api_proto_ipc_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_ipc_control_proto_rawDesc), len(file_api_proto_ipc_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_ipc_control_proto_goTypes,
		DependencyIndexes: file_api_proto_ipc_control_proto_depIdxs,
		MessageInfos:      file_api_proto_ipc_control_proto_msgTypes,
	}.Build()
	File_api_proto_ipc_control_proto = out.File
	file_api_proto_ipc_control_proto_goTypes = nil
	file_api_proto_ipc_control_proto_depIdxs = nil
}
