// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: api/proto/ipc/daemon.proto

package ipc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DaemonService_GetStatus_FullMethodName            = "/ipc.DaemonService/GetStatus"
	DaemonService_GetHealth_FullMethodName            = "/ipc.DaemonService/GetHealth"
	DaemonService_GetCompliance_FullMethodName        = "/ipc.DaemonService/GetCompliance"
	DaemonService_ListPatches_FullMethodName          = "/ipc.DaemonService/ListPatches"
	DaemonService_TriggerScan_FullMethodName          = "/ipc.DaemonService/TriggerScan"
	DaemonService_GetThreatStatus_FullMethodName      = "/ipc.DaemonService/GetThreatStatus"
	DaemonService_CheckDomain_FullMethodName          = "/ipc.DaemonService/CheckDomain"
	DaemonService_CheckIP_FullMethodName              = "/ipc.DaemonService/CheckIP"
	DaemonService_CheckBulk_FullMethodName            = "/ipc.DaemonService/CheckBulk"
	DaemonService_ListServices_FullMethodName         = "/ipc.DaemonService/ListServices"
	DaemonService_StartService_FullMethodName         = "/ipc.DaemonService/StartService"
	DaemonService_StopService_FullMethodName          = "/ipc.DaemonService/StopService"
	DaemonService_RestartService_FullMethodName       = "/ipc.DaemonService/RestartService"
	DaemonService_GetConfig_FullMethodName            = "/ipc.DaemonService/GetConfig"
	DaemonService_ReloadConfig_FullMethodName         = "/ipc.DaemonService/ReloadConfig"
	DaemonService_GetConnections_FullMethodName       = "/ipc.DaemonService/GetConnections"
	DaemonService_GetFileStatus_FullMethodName        = "/ipc.DaemonService/GetFileStatus"
	DaemonService_ListQuarantined_FullMethodName      = "/ipc.DaemonService/ListQuarantined"
	DaemonService_ListProcesses_FullMethodName        = "/ipc.DaemonService/ListProcesses"
	DaemonService_GetEvents_FullMethodName            = "/ipc.DaemonService/GetEvents"
	DaemonService_StreamEvents_FullMethodName         = "/ipc.DaemonService/StreamEvents"
	DaemonService_GetBeaconAnalysis_FullMethodName    = "/ipc.DaemonService/GetBeaconAnalysis"
	DaemonService_GetDNSTunnelAnalysis_FullMethodName = "/ipc.DaemonService/GetDNSTunnelAnalysis"
	DaemonService_ScanProcessMemory_FullMethodName    = "/ipc.DaemonService/ScanProcessMemory"
	DaemonService_GetMemoryScanResults_FullMethodName = "/ipc.DaemonService/GetMemoryScanResults"
	DaemonService_Shutdown_FullMethodName             = "/ipc.DaemonService/Shutdown"
)

// DaemonServiceClient is the client API for DaemonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DaemonServiceClient interface {
	// Status & Health
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	GetHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Patch Management
	GetCompliance(ctx context.Context, in *GetComplianceRequest, opts ...grpc.CallOption) (*ComplianceResponse, error)
	ListPatches(ctx context.Context, in *ListPatchesRequest, opts ...grpc.CallOption) (*PatchListResponse, error)
	TriggerScan(ctx context.Context, in *TriggerScanRequest, opts ...grpc.CallOption) (*ScanResponse, error)
	// Threat Intelligence
	GetThreatStatus(ctx context.Context, in *GetThreatStatusRequest, opts ...grpc.CallOption) (*ThreatStatusResponse, error)
	CheckDomain(ctx context.Context, in *CheckDomainRequest, opts ...grpc.CallOption) (*ThreatCheckResponse, error)
	CheckIP(ctx context.Context, in *CheckIPRequest, opts ...grpc.CallOption) (*ThreatCheckResponse, error)
	CheckBulk(ctx context.Context, in *CheckBulkRequest, opts ...grpc.CallOption) (*CheckBulkResponse, error)
	// Service Management
	ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ServiceListResponse, error)
	StartService(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error)
	StopService(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error)
	RestartService(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error)
	// Configuration
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error)
	ReloadConfig(ctx context.Context, in *ReloadConfigRequest, opts ...grpc.CallOption) (*ReloadResponse, error)
	// Network Monitoring
	GetConnections(ctx context.Context, in *GetConnectionsRequest, opts ...grpc.CallOption) (*ConnectionsResponse, error)
	// File Integrity
	GetFileStatus(ctx context.Context, in *GetFileStatusRequest, opts ...grpc.CallOption) (*FileStatusResponse, error)
	ListQuarantined(ctx context.Context, in *ListQuarantinedRequest, opts ...grpc.CallOption) (*QuarantinedResponse, error)
	// Process Monitoring
	ListProcesses(ctx context.Context, in *ListProcessesRequest, opts ...grpc.CallOption) (*ProcessListResponse, error)
	// Events & Logs
	GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*EventsResponse, error)
	StreamEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// C2/Beacon Detection
	GetBeaconAnalysis(ctx context.Context, in *GetBeaconAnalysisRequest, opts ...grpc.CallOption) (*BeaconAnalysisResponse, error)
	// DNS Tunneling Detection
	GetDNSTunnelAnalysis(ctx context.Context, in *GetDNSTunnelAnalysisRequest, opts ...grpc.CallOption) (*DNSTunnelAnalysisResponse, error)
	// Memory Scanning
	ScanProcessMemory(ctx context.Context, in *ScanProcessMemoryRequest, opts ...grpc.CallOption) (*MemoryScanResponse, error)
	GetMemoryScanResults(ctx context.Context, in *GetMemoryScanResultsRequest, opts ...grpc.CallOption) (*MemoryScanResultsResponse, error)
	// Daemon Control
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
}

type daemonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonServiceClient(cc grpc.ClientConnInterface) DaemonServiceClient {
	return &daemonServiceClient{cc}
}

func (c *daemonServiceClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetCompliance(ctx context.Context, in *GetComplianceRequest, opts ...grpc.CallOption) (*ComplianceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComplianceResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetCompliance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListPatches(ctx context.Context, in *ListPatchesRequest, opts ...grpc.CallOption) (*PatchListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatchListResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListPatches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) TriggerScan(ctx context.Context, in *TriggerScanRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, DaemonService_TriggerScan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetThreatStatus(ctx context.Context, in *GetThreatStatusRequest, opts ...grpc.CallOption) (*ThreatStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ThreatStatusResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetThreatStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) CheckDomain(ctx context.Context, in *CheckDomainRequest, opts ...grpc.CallOption) (*ThreatCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ThreatCheckResponse)
	err := c.cc.Invoke(ctx, DaemonService_CheckDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) CheckIP(ctx context.Context, in *CheckIPRequest, opts ...grpc.CallOption) (*ThreatCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ThreatCheckResponse)
	err := c.cc.Invoke(ctx, DaemonService_CheckIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) CheckBulk(ctx context.Context, in *CheckBulkRequest, opts ...grpc.CallOption) (*CheckBulkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckBulkResponse)
	err := c.cc.Invoke(ctx, DaemonService_CheckBulk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ServiceListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceListResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StartService(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, DaemonService_StartService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StopService(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, DaemonService_StopService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) RestartService(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, DaemonService_RestartService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ReloadConfig(ctx context.Context, in *ReloadConfigRequest, opts ...grpc.CallOption) (*ReloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadResponse)
	err := c.cc.Invoke(ctx, DaemonService_ReloadConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetConnections(ctx context.Context, in *GetConnectionsRequest, opts ...grpc.CallOption) (*ConnectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectionsResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetConnections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetFileStatus(ctx context.Context, in *GetFileStatusRequest, opts ...grpc.CallOption) (*FileStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileStatusResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetFileStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListQuarantined(ctx context.Context, in *ListQuarantinedRequest, opts ...grpc.CallOption) (*QuarantinedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuarantinedResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListQuarantined_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListProcesses(ctx context.Context, in *ListProcessesRequest, opts ...grpc.CallOption) (*ProcessListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessListResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListProcesses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*EventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventsResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StreamEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DaemonService_ServiceDesc.Streams[0], DaemonService_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetEventsRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_StreamEventsClient = grpc.ServerStreamingClient[Event]

func (c *daemonServiceClient) GetBeaconAnalysis(ctx context.Context, in *GetBeaconAnalysisRequest, opts ...grpc.CallOption) (*BeaconAnalysisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeaconAnalysisResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetBeaconAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetDNSTunnelAnalysis(ctx context.Context, in *GetDNSTunnelAnalysisRequest, opts ...grpc.CallOption) (*DNSTunnelAnalysisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DNSTunnelAnalysisResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetDNSTunnelAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ScanProcessMemory(ctx context.Context, in *ScanProcessMemoryRequest, opts ...grpc.CallOption) (*MemoryScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemoryScanResponse)
	err := c.cc.Invoke(ctx, DaemonService_ScanProcessMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetMemoryScanResults(ctx context.Context, in *GetMemoryScanResultsRequest, opts ...grpc.CallOption) (*MemoryScanResultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemoryScanResultsResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetMemoryScanResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, DaemonService_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaemonServiceServer is the server API for DaemonService service.
// All implementations must embed UnimplementedDaemonServiceServer
// for forward compatibility.
type DaemonServiceServer interface {
	// Status & Health
	GetStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	GetHealth(context.Context, *HealthRequest) (*HealthResponse, error)
	// Patch Management
	GetCompliance(context.Context, *GetComplianceRequest) (*ComplianceResponse, error)
	ListPatches(context.Context, *ListPatchesRequest) (*PatchListResponse, error)
	TriggerScan(context.Context, *TriggerScanRequest) (*ScanResponse, error)
	// Threat Intelligence
	GetThreatStatus(context.Context, *GetThreatStatusRequest) (*ThreatStatusResponse, error)
	CheckDomain(context.Context, *CheckDomainRequest) (*ThreatCheckResponse, error)
	CheckIP(context.Context, *CheckIPRequest) (*ThreatCheckResponse, error)
	CheckBulk(context.Context, *CheckBulkRequest) (*CheckBulkResponse, error)
	// Service Management
	ListServices(context.Context, *ListServicesRequest) (*ServiceListResponse, error)
	StartService(context.Context, *ServiceRequest) (*ServiceResponse, error)
	StopService(context.Context, *ServiceRequest) (*ServiceResponse, error)
	RestartService(context.Context, *ServiceRequest) (*ServiceResponse, error)
	// Configuration
	GetConfig(context.Context, *GetConfigRequest) (*ConfigResponse, error)
	ReloadConfig(context.Context, *ReloadConfigRequest) (*ReloadResponse, error)
	// Network Monitoring
	GetConnections(context.Context, *GetConnectionsRequest) (*ConnectionsResponse, error)
	// File Integrity
	GetFileStatus(context.Context, *GetFileStatusRequest) (*FileStatusResponse, error)
	ListQuarantined(context.Context, *ListQuarantinedRequest) (*QuarantinedResponse, error)
	// Process Monitoring
	ListProcesses(context.Context, *ListProcessesRequest) (*ProcessListResponse, error)
	// Events & Logs
	GetEvents(context.Context, *GetEventsRequest) (*EventsResponse, error)
	StreamEvents(*GetEventsRequest, grpc.ServerStreamingServer[Event]) error
	// C2/Beacon Detection
	GetBeaconAnalysis(context.Context, *GetBeaconAnalysisRequest) (*BeaconAnalysisResponse, error)
	// DNS Tunneling Detection
	GetDNSTunnelAnalysis(context.Context, *GetDNSTunnelAnalysisRequest) (*DNSTunnelAnalysisResponse, error)
	// Memory Scanning
	ScanProcessMemory(context.Context, *ScanProcessMemoryRequest) (*MemoryScanResponse, error)
	GetMemoryScanResults(context.Context, *GetMemoryScanResultsRequest) (*MemoryScanResultsResponse, error)
	// Daemon Control
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	mustEmbedUnimplementedDaemonServiceServer()
}

// UnimplementedDaemonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDaemonServiceServer struct{}

func (UnimplementedDaemonServiceServer) GetStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedDaemonServiceServer) GetHealth(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedDaemonServiceServer) GetCompliance(context.Context, *GetComplianceRequest) (*ComplianceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCompliance not implemented")
}
func (UnimplementedDaemonServiceServer) ListPatches(context.Context, *ListPatchesRequest) (*PatchListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPatches not implemented")
}
func (UnimplementedDaemonServiceServer) TriggerScan(context.Context, *TriggerScanRequest) (*ScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerScan not implemented")
}
func (UnimplementedDaemonServiceServer) GetThreatStatus(context.Context, *GetThreatStatusRequest) (*ThreatStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetThreatStatus not implemented")
}
func (UnimplementedDaemonServiceServer) CheckDomain(context.Context, *CheckDomainRequest) (*ThreatCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckDomain not implemented")
}
func (UnimplementedDaemonServiceServer) CheckIP(context.Context, *CheckIPRequest) (*ThreatCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckIP not implemented")
}
func (UnimplementedDaemonServiceServer) CheckBulk(context.Context, *CheckBulkRequest) (*CheckBulkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckBulk not implemented")
}
func (UnimplementedDaemonServiceServer) ListServices(context.Context, *ListServicesRequest) (*ServiceListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedDaemonServiceServer) StartService(context.Context, *ServiceRequest) (*ServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartService not implemented")
}
func (UnimplementedDaemonServiceServer) StopService(context.Context, *ServiceRequest) (*ServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopService not implemented")
}
func (UnimplementedDaemonServiceServer) RestartService(context.Context, *ServiceRequest) (*ServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartService not implemented")
}
func (UnimplementedDaemonServiceServer) GetConfig(context.Context, *GetConfigRequest) (*ConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedDaemonServiceServer) ReloadConfig(context.Context, *ReloadConfigRequest) (*ReloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReloadConfig not implemented")
}
func (UnimplementedDaemonServiceServer) GetConnections(context.Context, *GetConnectionsRequest) (*ConnectionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConnections not implemented")
}
func (UnimplementedDaemonServiceServer) GetFileStatus(context.Context, *GetFileStatusRequest) (*FileStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFileStatus not implemented")
}
func (UnimplementedDaemonServiceServer) ListQuarantined(context.Context, *ListQuarantinedRequest) (*QuarantinedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListQuarantined not implemented")
}
func (UnimplementedDaemonServiceServer) ListProcesses(context.Context, *ListProcessesRequest) (*ProcessListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProcesses not implemented")
}
func (UnimplementedDaemonServiceServer) GetEvents(context.Context, *GetEventsRequest) (*EventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEvents not implemented")
}
func (UnimplementedDaemonServiceServer) StreamEvents(*GetEventsRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedDaemonServiceServer) GetBeaconAnalysis(context.Context, *GetBeaconAnalysisRequest) (*BeaconAnalysisResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBeaconAnalysis not implemented")
}
func (UnimplementedDaemonServiceServer) GetDNSTunnelAnalysis(context.Context, *GetDNSTunnelAnalysisRequest) (*DNSTunnelAnalysisResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDNSTunnelAnalysis not implemented")
}
func (UnimplementedDaemonServiceServer) ScanProcessMemory(context.Context, *ScanProcessMemoryRequest) (*MemoryScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScanProcessMemory not implemented")
}
func (UnimplementedDaemonServiceServer) GetMemoryScanResults(context.Context, *GetMemoryScanResultsRequest) (*MemoryScanResultsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMemoryScanResults not implemented")
}
func (UnimplementedDaemonServiceServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedDaemonServiceServer) mustEmbedUnimplementedDaemonServiceServer() {}
func (UnimplementedDaemonServiceServer) testEmbeddedByValue()                       {}

// UnsafeDaemonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaemonServiceServer will
// result in compilation errors.
type UnsafeDaemonServiceServer interface {
	mustEmbedUnimplementedDaemonServiceServer()
}

func RegisterDaemonServiceServer(s grpc.ServiceRegistrar, srv DaemonServiceServer) {
	// If the following call panics, it indicates UnimplementedDaemonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DaemonService_ServiceDesc, srv)
}

func _DaemonService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetHealth(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetCompliance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetComplianceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetCompliance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetCompliance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetCompliance(ctx, req.(*GetComplianceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListPatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPatchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListPatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListPatches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListPatches(ctx, req.(*ListPatchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_TriggerScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).TriggerScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_TriggerScan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).TriggerScan(ctx, req.(*TriggerScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetThreatStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetThreatStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetThreatStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetThreatStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetThreatStatus(ctx, req.(*GetThreatStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_CheckDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).CheckDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_CheckDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).CheckDomain(ctx, req.(*CheckDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_CheckIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).CheckIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_CheckIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).CheckIP(ctx, req.(*CheckIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_CheckBulk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckBulkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).CheckBulk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_CheckBulk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).CheckBulk(ctx, req.(*CheckBulkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListServices(ctx, req.(*ListServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StartService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).StartService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_StartService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).StartService(ctx, req.(*ServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StopService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).StopService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_StopService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).StopService(ctx, req.(*ServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_RestartService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).RestartService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_RestartService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).RestartService(ctx, req.(*ServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ReloadConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ReloadConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ReloadConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ReloadConfig(ctx, req.(*ReloadConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetConnections(ctx, req.(*GetConnectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetFileStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetFileStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetFileStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetFileStatus(ctx, req.(*GetFileStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListQuarantined_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListQuarantinedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListQuarantined(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListQuarantined_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListQuarantined(ctx, req.(*ListQuarantinedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListProcesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProcessesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListProcesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListProcesses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListProcesses(ctx, req.(*ListProcessesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetEvents(ctx, req.(*GetEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonServiceServer).StreamEvents(m, &grpc.GenericServerStream[GetEventsRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_StreamEventsServer = grpc.ServerStreamingServer[Event]

func _DaemonService_GetBeaconAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBeaconAnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetBeaconAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetBeaconAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetBeaconAnalysis(ctx, req.(*GetBeaconAnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetDNSTunnelAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDNSTunnelAnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetDNSTunnelAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetDNSTunnelAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetDNSTunnelAnalysis(ctx, req.(*GetDNSTunnelAnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ScanProcessMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanProcessMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ScanProcessMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ScanProcessMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ScanProcessMemory(ctx, req.(*ScanProcessMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetMemoryScanResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemoryScanResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetMemoryScanResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetMemoryScanResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetMemoryScanResults(ctx, req.(*GetMemoryScanResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DaemonService_ServiceDesc is the grpc.ServiceDesc for DaemonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DaemonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ipc.DaemonService",
	HandlerType: (*DaemonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _DaemonService_GetStatus_Handler,
		},
		{
			MethodName: "GetHealth",
			Handler:    _DaemonService_GetHealth_Handler,
		},
		{
			MethodName: "GetCompliance",
			Handler:    _DaemonService_GetCompliance_Handler,
		},
		{
			MethodName: "ListPatches",
			Handler:    _DaemonService_ListPatches_Handler,
		},
		{
			MethodName: "TriggerScan",
			Handler:    _DaemonService_TriggerScan_Handler,
		},
		{
			MethodName: "GetThreatStatus",
			Handler:    _DaemonService_GetThreatStatus_Handler,
		},
		{
			MethodName: "CheckDomain",
			Handler:    _DaemonService_CheckDomain_Handler,
		},
		{
			MethodName: "CheckIP",
			Handler:    _DaemonService_CheckIP_Handler,
		},
		{
			MethodName: "CheckBulk",
			Handler:    _DaemonService_CheckBulk_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _DaemonService_ListServices_Handler,
		},
		{
			MethodName: "StartService",
			Handler:    _DaemonService_StartService_Handler,
		},
		{
			MethodName: "StopService",
			Handler:    _DaemonService_StopService_Handler,
		},
		{
			MethodName: "RestartService",
			Handler:    _DaemonService_RestartService_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _DaemonService_GetConfig_Handler,
		},
		{
			MethodName: "ReloadConfig",
			Handler:    _DaemonService_ReloadConfig_Handler,
		},
		{
			MethodName: "GetConnections",
			Handler:    _DaemonService_GetConnections_Handler,
		},
		{
			MethodName: "GetFileStatus",
			Handler:    _DaemonService_GetFileStatus_Handler,
		},
		{
			MethodName: "ListQuarantined",
			Handler:    _DaemonService_ListQuarantined_Handler,
		},
		{
			MethodName: "ListProcesses",
			Handler:    _DaemonService_ListProcesses_Handler,
		},
		{
			MethodName: "GetEvents",
			Handler:    _DaemonService_GetEvents_Handler,
		},
		{
			MethodName: "GetBeaconAnalysis",
			Handler:    _DaemonService_GetBeaconAnalysis_Handler,
		},
		{
			MethodName: "GetDNSTunnelAnalysis",
			Handler:    _DaemonService_GetDNSTunnelAnalysis_Handler,
		},
		{
			MethodName: "ScanProcessMemory",
			Handler:    _DaemonService_ScanProcessMemory_Handler,
		},
		{
			MethodName: "GetMemoryScanResults",
			Handler:    _DaemonService_GetMemoryScanResults_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _DaemonService_Shutdown_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _DaemonService_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/ipc/daemon.proto",
}
