image:
  repository: afterdark-darkd
  tag: "1.0.0"
  pullPolicy: IfNotPresent
persistence:
  size: 10Gi
  storageClass: ""
credentialsSecret: ""
telemetryEnabled: false
darkapiURL: https://api.darkapi.io
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: "1"
    memory: 512Mi
