//go:build linux

package ebpf

import (
	"context"
	"sync"
	"time"

	"github.com/afterdarksys/afterdark-darkd/internal/service"
	"github.com/afterdarksys/afterdark-darkd/pkg/logging"
	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/rlimit"
	"go.uber.org/zap"
)

const ServiceName = "ebpf_monitor"

type Config struct {
	Enabled bool `mapstructure:"enabled"`
}

type Service struct {
	config   *Config
	logger   *zap.Logger
	registry service.RegistryInterface

	objs *bpfObjects
	kp   link.Link

	mu      sync.RWMutex
	running bool
}

// bpfObjects matches the structure generated by bpf2go (stubbed here for manual loading if needed)
type bpfObjects struct {
	TraceExecve *ebpf.Program `ebpf:"trace_execve"`
}

func New(config *Config, registry service.RegistryInterface) (*Service, error) {
	if config == nil {
		config = &Config{Enabled: true}
	}

	return &Service{
		config:   config,
		logger:   logging.With(zap.String("service", ServiceName)),
		registry: registry,
	}, nil
}

func (s *Service) Name() string {
	return ServiceName
}

func (s *Service) Start(ctx context.Context) error {
	s.mu.Lock()
	defer s.mu.Unlock()

	if s.running {
		return nil
	}

	// Allow current process to lock memory for eBPF resources.
	if err := rlimit.RemoveMemlock(); err != nil {
		s.logger.Warn("failed to remove memlock limit", zap.Error(err))
	}

	// STUB: In a real environment, we would use LoadBpfObjects() generated by bpf2go
	// Since we don't have the ELF file, we will just simulate success or log a warning
	// s.objs = &bpfObjects{}
	// if err := loadBpfObjects(s.objs, nil); err != nil { ... }

	s.logger.Info("starting process monitor (ebpf)")
	s.running = true
	return nil
}

func (s *Service) Stop(ctx context.Context) error {
	s.mu.Lock()
	defer s.mu.Unlock()

	if !s.running {
		return nil
	}

	if s.kp != nil {
		s.kp.Close()
	}
	if s.objs != nil {
		// s.objs.Close()
	}

	s.running = false
	s.logger.Info("stopped ebpf service")
	return nil
}

func (s *Service) Configure(config interface{}) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if cfg, ok := config.(*Config); ok {
		s.config = cfg
	}
	return nil
}

func (s *Service) Health() service.HealthStatus {
	s.mu.RLock()
	defer s.mu.RUnlock()

	status := service.HealthHealthy
	msg := "ebpf probes active"

	if !s.running {
		status = service.HealthUnhealthy
		msg = "service stopped"
	}

	return service.HealthStatus{
		Status:    status,
		Message:   msg,
		LastCheck: time.Now(),
	}
}
