//go:build linux

package linux

import (
	"context"
	"fmt"
	"io"
	"net"
	"net/http"
	"os"
	"os/exec"
	"runtime"
	"strings"
	"syscall"
	"time"

	"github.com/afterdarksys/afterdark-darkd/internal/platform"
)

// Platform implements the platform.Platform interface for Linux
type Platform struct {
	distro string
	osInfo *platform.OSInfo
}

// New creates a new Linux platform implementation
func New() (*Platform, error) {
	distro := detectDistro()
	p := &Platform{distro: distro}
	// Pre-cache OS info
	info, err := p.GetOSInfo()
	if err == nil {
		p.osInfo = info
	}
	return p, nil
}

func detectDistro() string {
	// Check for /etc/os-release
	data, err := os.ReadFile("/etc/os-release")
	if err != nil {
		return "unknown"
	}

	lines := strings.Split(string(data), "\n")
	for _, line := range lines {
		if strings.HasPrefix(line, "ID=") {
			return strings.Trim(strings.TrimPrefix(line, "ID="), "\"")
		}
	}
	return "unknown"
}

// GetOSInfo returns Linux system information using native APIs
// instead of exec.Command("uname")
func (p *Platform) GetOSInfo() (*platform.OSInfo, error) {
	// Get kernel version using syscall.Uname instead of exec.Command("uname")
	var uname syscall.Utsname
	if err := syscall.Uname(&uname); err != nil {
		return nil, err
	}

	// Convert [65]int8 to string (Linux uses 65-byte arrays)
	kernelVersion := int8ArrayToString(uname.Release[:])

	// Get OS name and version from /etc/os-release (already native)
	name := "Linux"
	version := "unknown"
	build := ""

	data, err := os.ReadFile("/etc/os-release")
	if err == nil {
		lines := strings.Split(string(data), "\n")
		for _, line := range lines {
			if strings.HasPrefix(line, "NAME=") {
				name = strings.Trim(strings.TrimPrefix(line, "NAME="), "\"")
			}
			if strings.HasPrefix(line, "VERSION_ID=") {
				version = strings.Trim(strings.TrimPrefix(line, "VERSION_ID="), "\"")
			}
			if strings.HasPrefix(line, "BUILD_ID=") {
				build = strings.Trim(strings.TrimPrefix(line, "BUILD_ID="), "\"")
			}
		}
	}

	return &platform.OSInfo{
		Name:         name,
		Version:      version,
		Build:        build,
		Architecture: runtime.GOARCH,
		Kernel:       kernelVersion,
	}, nil
}

// int8ArrayToString converts a null-terminated int8 array to string
func int8ArrayToString(arr []int8) string {
	b := make([]byte, 0, len(arr))
	for _, v := range arr {
		if v == 0 {
			break
		}
		b = append(b, byte(v))
	}
	return string(b)
}

// GetHostname returns the system hostname
func (p *Platform) GetHostname() (string, error) {
	return os.Hostname()
}

// Methods moved to patches.go

// GetNetworkInterfaces returns network interfaces using net.Interfaces()
func (p *Platform) GetNetworkInterfaces() ([]platform.NetworkInterface, error) {
	ifaces, err := net.Interfaces()
	if err != nil {
		return nil, err
	}
	var result []platform.NetworkInterface
	for _, iface := range ifaces {
		ni := platform.NetworkInterface{
			Name:       iface.Name,
			MACAddress: iface.HardwareAddr.String(),
			Status:     iface.Flags.String(),
		}
		addrs, _ := iface.Addrs()
		if len(addrs) > 0 {
			ni.IPAddress = addrs[0].String()
		}
		result = append(result, ni)
	}
	return result, nil
}

// GetPublicIP returns the public IP address by querying an external service
func (p *Platform) GetPublicIP(ctx context.Context) (string, error) {
	client := &http.Client{Timeout: 5 * time.Second}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, "https://api.ipify.org", nil)
	if err != nil {
		return "", err
	}
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(body)), nil
}

// SetDNSServers configures DNS servers.
// Tries systemd-resolved (resolvectl) first; falls back to writing /etc/resolv.conf.
func (p *Platform) SetDNSServers(servers []string) error {
	// Attempt resolvectl on every non-loopback interface
	ifaces, _ := net.Interfaces()
	applied := 0
	for _, iface := range ifaces {
		if iface.Flags&net.FlagLoopback != 0 {
			continue
		}
		args := append([]string{"dns", iface.Name}, servers...)
		if err := exec.CommandContext(context.Background(), "resolvectl", args...).Run(); err == nil {
			applied++
		}
	}
	if applied > 0 {
		return nil
	}
	// Fall back to /etc/resolv.conf
	var content strings.Builder
	content.WriteString("# Generated by afterdark-darkd\n")
	for _, s := range servers {
		content.WriteString(fmt.Sprintf("nameserver %s\n", s))
	}
	return os.WriteFile("/etc/resolv.conf", []byte(content.String()), 0644)
}

// EnableFirewall enables the Linux firewall.
// Tries nftables first, falls back to iptables.
func (p *Platform) EnableFirewall() error {
	if err := exec.CommandContext(context.Background(), "nft", "add", "table", "inet", "filter").Run(); err == nil {
		return nil
	}
	return exec.CommandContext(context.Background(), "iptables", "-P", "INPUT", "DROP").Run()
}

// DisableICMP controls whether the host responds to ICMP echo requests.
// When enabled is true, ICMP echo is suppressed via sysctl.
// When enabled is false, it is restored to default (0 = respond).
func (p *Platform) DisableICMP(enabled bool) error {
	value := "1"
	if !enabled {
		value = "0"
	}
	return exec.CommandContext(context.Background(),
		"sysctl", "-w", fmt.Sprintf("net.ipv4.icmp_echo_ignore_all=%s", value)).Run()
}

// BlockIPFragmentation controls whether IP fragments are dropped in the FORWARD chain.
// When enabled is true, a DROP rule is appended; when false, the rule is removed.
func (p *Platform) BlockIPFragmentation(enabled bool) error {
	action := "-A"
	if !enabled {
		action = "-D"
	}
	return exec.CommandContext(context.Background(),
		"iptables", action, "FORWARD", "-f", "-j", "DROP").Run()
}
